// _js/cataleg.js - Dades del catàleg generades automàticament per _scripts/sync-catalog.py
// No editeu manualment aquest fitxer; s'actualitza amb el script o mitjançant el git hook.
window.CATALEG = {
  "activitats": [
    {
      "id": "activitat-bucles-coreografia",
      "slug": "bucles-coreografia",
      "url": "activitat/index.html?id=bucles-coreografia",
      "titol": "La Coreografia dels Bucles",
      "tag": "Bucles i Repetició",
      "cicle": "Primer, segon i tercer cicle",
      "durada": "45 min",
      "descripcio": "Repetiu una seqüència de moviments i busqueu la manera més clara d'explicar-la amb poques instruccions."
    },
    {
      "id": "activitat-condicionals-moviment",
      "slug": "condicionals-moviment",
      "url": "activitat/index.html?id=condicionals-moviment",
      "titol": "El joc dels condicionals: si... llavors... si no...",
      "tag": "Estructures de Control Condicional",
      "cicle": "Tots els cicles",
      "durada": "35 min",
      "descripcio": "Practiqueu les decisions amb targetes inventades i representeu què passa quan una condició és certa o falsa."
    },
    {
      "id": "activitat-criptografia-cesar",
      "slug": "criptografia-cesar",
      "url": "activitat/index.html?id=criptografia-cesar",
      "titol": "Missatges Secrets i Xifratge Cèsar",
      "tag": "Ciberseguretat i Criptografia",
      "cicle": "Segon i tercer cicle",
      "durada": "50 min",
      "descripcio": "Construcció d'una roda de xifratge de dos cercles concèntrics per comprendre com es protegeix la informació"
    },
    {
      "id": "activitat-dades-classificacio",
      "slug": "dades-classificacio",
      "url": "activitat/index.html?id=dades-classificacio",
      "titol": "El Museu de les Dades",
      "tag": "Dades, Classificació i Privadesa",
      "cicle": "Primer, segon i tercer cicle",
      "durada": "50 min",
      "descripcio": "Recolliu dades inventades, trieu com classificar-les i representeu-les amb una regla clara."
    },
    {
      "id": "activitat-descomposicio-receptes",
      "slug": "descomposicio-receptes",
      "url": "activitat/index.html?id=descomposicio-receptes",
      "titol": "Receptes amb Instruccions de Robot",
      "tag": "Descomposició i Algorismes",
      "cicle": "Primer, segon i tercer cicle",
      "durada": "50 min",
      "descripcio": "Descomposeu una tasca quotidiana en instruccions precises i proveu què passa si en canvieu l'ordre."
    },
    {
      "id": "activitat-laberint-debugging",
      "slug": "laberint-debugging",
      "url": "activitat/index.html?id=laberint-debugging",
      "titol": "El Laberint d'Instruccions i Detecció d'Errors",
      "tag": "Depuració (Debugging) i Seqüenciació",
      "cicle": "Educació Infantil i primer cicle",
      "durada": "40 min",
      "descripcio": "Sobre una graella gegant al terra amb fitxes de cartolina, els alumnes col·loquen targetes de fletxes"
    },
    {
      "id": "activitat-patrons-simetries",
      "slug": "patrons-simetries",
      "url": "activitat/index.html?id=patrons-simetries",
      "titol": "Detectius de Patrons i Repeticions",
      "tag": "Patrons i Abstracció",
      "cicle": "Educació Infantil, primer i segon cicle",
      "durada": "40 min",
      "descripcio": "Observeu seqüències de formes i sons, expliqueu la regla i predigueu quin element ve després."
    },
    {
      "id": "activitat-pixels-binaris",
      "slug": "pixels-binaris",
      "url": "activitat/index.html?id=pixels-binaris",
      "titol": "Dibuix per Píxels i Imatges Binàries",
      "tag": "Representació de Dades (Binari)",
      "cicle": "Primer i segon cicle",
      "durada": "45 min",
      "descripcio": "Com 'veu' i guarda un ordinador un dibuix? L'alumnat codifica i descodifica imatges senzilles en quadrícules"
    },
    {
      "id": "activitat-robot-huma",
      "slug": "robot-huma",
      "url": "activitat/index.html?id=robot-huma",
      "titol": "El Robot Humà i el Llenguatge Precís",
      "tag": "Algorismes i Precisió",
      "cicle": "Educació Infantil i primer cicle",
      "durada": "45 min",
      "descripcio": "Una persona interpreta el robot sobre una graella, i una altra programa un recorregut amb"
    },
    {
      "id": "activitat-xarxa-ordenacio",
      "slug": "xarxa-ordenacio",
      "url": "activitat/index.html?id=xarxa-ordenacio",
      "titol": "Xarxa d'Ordenació al Terra (Sorting Networks)",
      "tag": "Algorismes de Comparació i Processament Paral·lel",
      "cicle": "Segon i tercer cicle",
      "durada": "50 min",
      "descripcio": "Dibuixem una xarxa de línies amb guix al pati. Sis alumnes amb números desordenats avancen per les"
    }
  ],
  "situacions": [
    {
      "id": "situacio-sa-ce-bifurcacio-parc",
      "slug": "ce-bifurcacio-parc",
      "url": "situacio/index.html?id=ce-bifurcacio-parc",
      "titol": "Dues rutes, una decisió",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "ciutat",
      "tematicaLabel": "Ciutat intel·ligent i accessibilitat",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques i Descoberta de l’entorn",
      "sessions": "3 sessions · 120 min",
      "repte": "Quina informació ens ajuda a decidir per quina branca ha de continuar el tren i com comprovem si ha arribat al destí triat?"
    },
    {
      "id": "situacio-sa-ce-bucle-horta",
      "slug": "ce-bucle-horta",
      "url": "situacio/index.html?id=ce-bucle-horta",
      "titol": "El bucle de l’horta escolar",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Medi ambient i sostenibilitat",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques i Descoberta de l’entorn",
      "sessions": "3 sessions · 120 min",
      "repte": "Què es repeteix quan el tren completa una volta a l’hort i com podem anticipar quantes vegades passarà pel mateix punt?"
    },
    {
      "id": "situacio-sa-ce-bucles-relats",
      "slug": "ce-bucles-relats",
      "url": "situacio/index.html?id=ce-bucles-relats",
      "titol": "El tren que torna",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "repeticio",
      "tematicaLabel": "Bucles i patrons que es repeteixen",
      "materia": "pensament-computacional",
      "materiaLabel": "Pensament computacional, música i llenguatge",
      "sessions": "4 sessions de 30–40 minuts",
      "repte": "Com podem representar una repetició amb una ruta i explicar quan deixa de repetir-se?"
    },
    {
      "id": "situacio-sa-ce-cami-segur",
      "slug": "ce-cami-segur",
      "url": "situacio/index.html?id=ce-cami-segur",
      "titol": "Un camí tranquil fins a l’escola",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "ciutat",
      "tematicaLabel": "Ciutat intel·ligent i accessibilitat",
      "materia": "medi",
      "materiaLabel": "Descoberta de l’entorn",
      "sessions": "3 sessions",
      "repte": "Quines situacions poden interrompre un trajecte i com podem representar decisions prudents en una maqueta sense confondre-la amb una senyalització real?"
    },
    {
      "id": "situacio-sa-ce-concert-pati",
      "slug": "ce-concert-pati",
      "url": "situacio/index.html?id=ce-concert-pati",
      "titol": "Un concert de sons del pati",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "art",
      "tematicaLabel": "Art, música i expressió",
      "materia": "artistica",
      "materiaLabel": "Educació Artística i Música",
      "sessions": "3 sessions",
      "repte": "Com podem crear una seqüència sonora breu inspirada en el pati i ordenar-la perquè cada so aparega en el moment acordat?"
    },
    {
      "id": "situacio-sa-ce-distancies-estacions",
      "slug": "ce-distancies-estacions",
      "url": "situacio/index.html?id=ce-distancies-estacions",
      "titol": "Distàncies entre estacions",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "ciutat",
      "tematicaLabel": "Mobilitat quotidiana i orientació",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques i Descoberta de l’entorn",
      "sessions": "3 sessions",
      "repte": "Quin nombre de l’app necessita el tren per arribar a cada estació i com comprovem que ha fet el trajecte esperat?"
    },
    {
      "id": "situacio-sa-ce-habitats-albufera",
      "slug": "ce-habitats-albufera",
      "url": "situacio/index.html?id=ce-habitats-albufera",
      "titol": "Hàbitats vius de l’Albufera",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Biodiversitat i cura de l’entorn",
      "materia": "medi",
      "materiaLabel": "Descoberta de l’entorn, Ciències i Llenguatge",
      "sessions": "5 sessions",
      "repte": "Què necessiten els éssers vius per habitar un lloc, i com podem representar canvis que ajuden a conservar-lo?"
    },
    {
      "id": "situacio-sa-ce-missatges-estacio",
      "slug": "ce-missatges-estacio",
      "url": "situacio/index.html?id=ce-missatges-estacio",
      "titol": "Missatges per a l’estació",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "llengua",
      "tematicaLabel": "Llengua i comunicació",
      "materia": "llengua",
      "materiaLabel": "Llengua i Literatura",
      "sessions": "3 sessions · 120 min",
      "repte": "Quina informació necessita cada estació per rebre el tren i com podem transmetre-la amb sons o símbols que tot el grup entenga?"
    },
    {
      "id": "situacio-sa-ce-oratge-pati",
      "slug": "ce-oratge-pati",
      "url": "situacio/index.html?id=ce-oratge-pati",
      "titol": "Un pati per a cada oratge",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "entorn",
      "tematicaLabel": "Oratge, estacions i espais de joc",
      "materia": "medi",
      "materiaLabel": "Descoberta de l’entorn, Ciències i Llenguatge",
      "sessions": "5 sessions",
      "repte": "Com podem preparar un pati acollidor per a diferents condicions d’oratge?"
    },
    {
      "id": "situacio-sa-ce-parades-emocions",
      "slug": "ce-parades-emocions",
      "url": "situacio/index.html?id=ce-parades-emocions",
      "titol": "Com se sent el personatge del tren?",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "societat",
      "tematicaLabel": "Convivència i ciutadania",
      "materia": "llengua",
      "materiaLabel": "Llengua i Educació emocional",
      "sessions": "3 sessions · 120 min",
      "repte": "Com podem escoltar diferents interpretacions d’un personatge de ficció i representar-les sense decidir què sent una persona real?"
    },
    {
      "id": "situacio-sa-ce-primer-viatge",
      "slug": "ce-primer-viatge",
      "url": "situacio/index.html?id=ce-primer-viatge",
      "titol": "Explorem les peces de la via",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "societat",
      "tematicaLabel": "Convivència i ciutadania",
      "materia": "medi",
      "materiaLabel": "Descoberta de l’entorn",
      "sessions": "3 sessions",
      "repte": "Quins elements necessitem per preparar una ruta clara perquè el tren visite una estació i puga tornar al punt de partida?"
    },
    {
      "id": "situacio-sa-ce-reptes-desconnectats",
      "slug": "ce-reptes-desconnectats",
      "url": "situacio/index.html?id=ce-reptes-desconnectats",
      "titol": "El tren es queda al taller",
      "robot": "desendollat",
      "robotLabel": "Activitat desconnectada",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "desconnectada",
      "tematicaLabel": "Seqüències sense pantalles ni robot",
      "materia": "pensament-computacional",
      "materiaLabel": "Pensament computacional, llenguatge i matemàtiques",
      "sessions": "4 sessions",
      "repte": "Podem resoldre els mateixos reptes amb el cos, targetes i paper?"
    },
    {
      "id": "situacio-sa-ce-reptes-rutes",
      "slug": "ce-reptes-rutes",
      "url": "situacio/index.html?id=ce-reptes-rutes",
      "titol": "Rutes amb decisions",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "resolucio-problemes",
      "tematicaLabel": "Sistemes, rutes i resolució de problemes",
      "materia": "pensament-computacional",
      "materiaLabel": "Pensament computacional, descoberta de l’entorn i llenguatge",
      "sessions": "4 sessions",
      "repte": "Com dissenyem una ruta comprensible i la millorem quan apareix un problema?"
    },
    {
      "id": "situacio-sa-ce-sequencia-histories",
      "slug": "ce-sequencia-histories",
      "url": "situacio/index.html?id=ce-sequencia-histories",
      "titol": "Històries que viatgen en tren",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "narracio",
      "tematicaLabel": "Seqüències, sons i relats",
      "materia": "llengua",
      "materiaLabel": "Llenguatge, descoberta de l’entorn i pensament computacional",
      "sessions": "5 sessions",
      "repte": "Quina seqüència d’ordres permet contar una història clara amb el tren?"
    },
    {
      "id": "situacio-sa-ciutat-accessible",
      "slug": "ciutat-accessible",
      "url": "situacio/index.html?id=ciutat-accessible",
      "titol": "Senyalització inclusiva en una maqueta",
      "robot": "microbit",
      "robotLabel": "Micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "ciutat",
      "tematicaLabel": "Accessibilitat i disseny urbà",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Coneixement del Medi i Disseny",
      "sessions": "6 sessions",
      "repte": "Com podem representar dos estats d’un pas urbà amb senyals comprensibles per més d’un canal i provar-los en una maqueta?"
    },
    {
      "id": "situacio-sa-coding-set-casa-geometrica",
      "slug": "coding-set-casa-geometrica",
      "url": "situacio/index.html?id=coding-set-casa-geometrica",
      "titol": "Un plànol geomètric amb MatataBot",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "art",
      "tematicaLabel": "Art, música i expressió",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques",
      "sessions": "4 sessions",
      "repte": "Quantes ordres necessitem per dibuixar el contorn d’una casa i com podem simplificar el programa quan repetim moviments?"
    },
    {
      "id": "situacio-sa-coding-set-fira-matematica",
      "slug": "coding-set-fira-matematica",
      "url": "situacio/index.html?id=coding-set-fira-matematica",
      "titol": "La fira de formes, nombres i estrelles",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "ciencia",
      "tematicaLabel": "Ciència i entorn",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques, llengües i educació artística",
      "sessions": "5 sessions",
      "repte": "Com podem convertir les ordres de MatataBot en una fira on classifiquem formes, escrivim nombres i dibuixem constel·lacions?"
    },
    {
      "id": "situacio-sa-coding-set-futbol-cooperatiu",
      "slug": "coding-set-futbol-cooperatiu",
      "url": "situacio/index.html?id=coding-set-futbol-cooperatiu",
      "titol": "Un repte cooperatiu de futbol de taula",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "societat",
      "tematicaLabel": "Convivència i ciutadania",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques i Educació Física",
      "sessions": "4 sessions",
      "repte": "Com podem programar una ruta de passada perquè la pilota arribe a una zona acordada i tothom puga participar en el repte?"
    },
    {
      "id": "situacio-sa-coding-set-parc-observadors",
      "slug": "coding-set-parc-observadors",
      "url": "situacio/index.html?id=coding-set-parc-observadors",
      "titol": "Una ronda d’observació al parc",
      "robot": "coding-set",
      "robotLabel": "MatataBot · Coding Set",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Natura pròxima i sostenibilitat",
      "materia": "medi",
      "materiaLabel": "Coneixement del Medi, Matemàtiques i Tecnologia",
      "sessions": "4 sessions",
      "repte": "Com podem programar una ruta que visite diversos espais i ens ajude a observar-los sense tocar ni molestar els éssers vius?"
    },
    {
      "id": "situacio-sa-coding-set-ruta-biblioteca",
      "slug": "coding-set-ruta-biblioteca",
      "url": "situacio/index.html?id=coding-set-ruta-biblioteca",
      "titol": "La ruta dels llibres viatgers",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "societat",
      "tematicaLabel": "Convivència i ciutadania",
      "materia": "llengua",
      "materiaLabel": "Llengua i Literatura",
      "sessions": "4 sessions · 180 min",
      "repte": "Com podem dissenyar un recorregut per portar un llibre fictici a tres espais i inventar una recomanació sense copiar cap sinopsi?"
    },
    {
      "id": "situacio-sa-conte-tale-bot",
      "slug": "conte-tale-bot",
      "url": "situacio/index.html?id=conte-tale-bot",
      "titol": "El pont de la marjal",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot Pro",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "narracio",
      "tematicaLabel": "Contes, seqüències i entorn valencià",
      "materia": "llengua",
      "materiaLabel": "Llenguatge, Educació Artística i Pensament Computacional",
      "sessions": "4 sessions",
      "repte": "Com podem ordenar les escenes i les ordres perquè Tale-Bot travesse el pont i altres persones puguen seguir el nostre conte?"
    },
    {
      "id": "situacio-sa-coreografia-codey",
      "slug": "coreografia-codey",
      "url": "situacio/index.html?id=coreografia-codey",
      "titol": "Una dansa robòtica per a la festa de l’escola",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "art",
      "tematicaLabel": "Ritme, dansa i expressió",
      "materia": "artistica",
      "materiaLabel": "Educació Artística, Música i Tecnologia",
      "sessions": "4 sessions",
      "repte": "Com podem convertir un ritme propi en una seqüència de moviments, expressions i llums que el robot puga repetir?"
    },
    {
      "id": "situacio-sa-cr-entrades-sensors",
      "slug": "cr-entrades-sensors",
      "url": "situacio/index.html?id=cr-entrades-sensors",
      "titol": "El laboratori de sensors de Codey Rocky",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "tecnologia",
      "tematicaLabel": "Sensors i interacció",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Ciències",
      "sessions": "12 sessions",
      "repte": "Com pot Codey Rocky percebre senyals del seu entorn i convertir-los en respostes que siguen útils, clares i comprovables?"
    },
    {
      "id": "situacio-sa-cr-llum-aula",
      "slug": "cr-llum-aula",
      "url": "situacio/index.html?id=cr-llum-aula",
      "titol": "El mapa de llum de l’aula",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Entorn escolar i ús responsable de l’energia",
      "materia": "medi",
      "materiaLabel": "Coneixement del Medi, Ciències i Tecnologia",
      "sessions": "4 sessions",
      "repte": "Com podem comparar la llum de diferents espais amb un procediment repetible i explicar els límits de la mesura?"
    },
    {
      "id": "situacio-sa-cr-mapa-sonor",
      "slug": "cr-mapa-sonor",
      "url": "situacio/index.html?id=cr-mapa-sonor",
      "titol": "Un mapa sonor per a llegir l’aula",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "benestar",
      "tematicaLabel": "Entorn sonor i benestar compartit",
      "materia": "medi",
      "materiaLabel": "Coneixement del Medi, Matemàtiques i Tecnologia",
      "sessions": "5 sessions · 225–250 min",
      "repte": "Com podem descriure i comparar l’ambient sonor d’un espai sense identificar qui parla ni confondre una lectura del sensor amb una mesura clínica o en decibels?"
    },
    {
      "id": "situacio-sa-cr-museu-jocs-programats",
      "slug": "cr-museu-jocs-programats",
      "url": "situacio/index.html?id=cr-museu-jocs-programats",
      "titol": "Museu de jocs programats",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "programacio",
      "tematicaLabel": "Projectes interactius i robòtica",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques, Art i Pensament Computacional",
      "sessions": "24 sessions de 40 minuts",
      "repte": "Com dissenyem una exposició de jocs que es puga entendre, provar, depurar i recórrer amb Codey Rocky?"
    },
    {
      "id": "situacio-sa-cr-repartiment",
      "slug": "cr-repartiment",
      "url": "situacio/index.html?id=cr-repartiment",
      "titol": "Repartiment amb una ruta segura",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "ciutat",
      "tematicaLabel": "Entorn i mobilitat",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques i Tecnologia",
      "sessions": "4 sessions",
      "repte": "Com pot un vehicle programat avançar per una ruta de repartiment i reaccionar davant d’un obstacle previsible?"
    },
    {
      "id": "situacio-sa-cr-ruta-colors",
      "slug": "cr-ruta-colors",
      "url": "situacio/index.html?id=cr-ruta-colors",
      "titol": "Arxiu de colors de l’horta",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Medi ambient i sostenibilitat",
      "materia": "medi",
      "materiaLabel": "Coneixement del Medi / Ciències",
      "sessions": "4 sessions",
      "repte": "Com podem descriure i classificar els colors que observem a l’horta sense confondre una lectura del sensor amb la identificació d’un objecte?"
    },
    {
      "id": "situacio-sa-cs-estacions-codi",
      "slug": "cs-estacions-codi",
      "url": "situacio/index.html?id=cs-estacions-codi",
      "titol": "Estacions de codi: del bloc al mapa",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "entorn-local",
      "tematicaLabel": "Entorn i comunitat",
      "materia": "pensament-computacional",
      "materiaLabel": "Pensament computacional, llengües i expressió artística",
      "sessions": "12 sessions de 45 minuts",
      "repte": "Com podem passar d’unes ordres tangibles a una història i un mapa que una altra classe puga comprendre i recórrer?"
    },
    {
      "id": "situacio-sa-desendollada-cripto",
      "slug": "desendollada-cripto",
      "url": "situacio/index.html?id=desendollada-cripto",
      "titol": "Espies escolars: missatges i privacitat",
      "robot": "desendollat",
      "robotLabel": "Desendollat (sense robot)",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "societat",
      "tematicaLabel": "Convivència i ciutadania digital",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques",
      "sessions": "4 sessions de 50 minuts",
      "repte": "Com podem transmetre un missatge de manera que el destinatari el puga recuperar, i què ens ensenya això sobre la privacitat digital?"
    },
    {
      "id": "situacio-sa-emocions-codey",
      "slug": "emocions-codey",
      "url": "situacio/index.html?id=emocions-codey",
      "titol": "Caretes de la plaça",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "salut",
      "tematicaLabel": "Benestar i convivència",
      "materia": "llengua",
      "materiaLabel": "Llengua, Educació Artística i Tecnologia",
      "sessions": "4 sessions",
      "repte": "Com pot una expressió digital ajudar-nos a contar una història, i per què no és suficient per saber com se sent una persona?"
    },
    {
      "id": "situacio-sa-hivernacle-microbit",
      "slug": "hivernacle-microbit",
      "url": "situacio/index.html?id=hivernacle-microbit",
      "titol": "Alertes per al bosc i l’hort",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Biodiversitat i cultiu",
      "materia": "medi",
      "materiaLabel": "Ciències, Tecnologia i Matemàtiques",
      "sessions": "4 sessions · 200 min",
      "repte": "Com podem enviar un avís de protecció i representar un sensor de cultiu sense exposar la placa a l’aigua o al sòl?"
    },
    {
      "id": "situacio-sa-laberint-mart",
      "slug": "laberint-mart",
      "url": "situacio/index.html?id=laberint-mart",
      "titol": "Missió de robòtica cooperativa",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "entorn",
      "tematicaLabel": "L’Albufera i la cura de l’entorn",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Ciències",
      "sessions": "12–15 sessions",
      "repte": "Com podem dissenyar un robot fiable que complete missions de cura de l’entorn i explique amb proves les decisions de l’equip?"
    },
    {
      "id": "situacio-sa-mb-animacio-volca",
      "slug": "mb-animacio-volca",
      "url": "situacio/index.html?id=mb-animacio-volca",
      "titol": "Una erupció en píxels",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "ciencia",
      "tematicaLabel": "Fenòmens geològics i animació",
      "materia": "medi",
      "materiaLabel": "Ciències, Geografia i Tecnologia",
      "sessions": "5 sessions · 225 min",
      "repte": "Com podem descompondre un procés en fotogrames i repetir-los en una animació LED comprensible?"
    },
    {
      "id": "situacio-sa-mb-animacions-aiguamoll",
      "slug": "mb-animacions-aiguamoll",
      "url": "situacio/index.html?id=mb-animacions-aiguamoll",
      "titol": "Animacions de l’aiguamoll",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "natura",
      "tematicaLabel": "Natura i expressió digital",
      "materia": "artistica",
      "materiaLabel": "Educació Artística, Medi i Tecnologia",
      "sessions": "2 sessions · 100 min",
      "repte": "Com podem explicar una observació de la natura amb una icona LED i una animació programada?"
    },
    {
      "id": "situacio-sa-mb-art-de-la-natura",
      "slug": "mb-art-de-la-natura",
      "url": "situacio/index.html?id=mb-art-de-la-natura",
      "titol": "Art de la natura en píxels",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "natura",
      "tematicaLabel": "Observació i representació",
      "materia": "artistica",
      "materiaLabel": "Educació Artística, Medi i Tecnologia",
      "sessions": "4 sessions · 180 min",
      "repte": "Quins trets d’una forma natural podem conservar quan la representem primer amb materials i després amb cinc per cinc píxels?"
    },
    {
      "id": "situacio-sa-mb-aula-sensorial",
      "slug": "mb-aula-sensorial",
      "url": "situacio/index.html?id=mb-aula-sensorial",
      "titol": "Una aula amb opcions sensorials",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "ciutadania",
      "tematicaLabel": "Disseny accessible",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Ciències i Inclusió",
      "sessions": "4 sessions · 200 min",
      "repte": "Com podem crear un recurs visual opcional i configurable que ajude a fer més previsible una rutina de l’aula?"
    },
    {
      "id": "situacio-sa-mb-clau-segura",
      "slug": "mb-clau-segura",
      "url": "situacio/index.html?id=mb-clau-segura",
      "titol": "Clau segura, dades protegides",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "ciutadania",
      "tematicaLabel": "Seguretat i privacitat",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Ciutadania Digital",
      "sessions": "4 sessions · 200 min",
      "repte": "Com podem explicar els riscos digitals i provar un algorisme de contrasenyes amb dades completament fictícies?"
    },
    {
      "id": "situacio-sa-mb-comptador-residus",
      "slug": "mb-comptador-residus",
      "url": "situacio/index.html?id=mb-comptador-residus",
      "titol": "Comptem residus amb cura",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Residus i entorn escolar",
      "materia": "medi",
      "materiaLabel": "Medi, Matemàtiques i Tecnologia",
      "sessions": "3 sessions · 150 min",
      "repte": "Com podem dissenyar un comptador de micro:bit que registre residus per categoria i ens ajude a fer una proposta responsable?"
    },
    {
      "id": "situacio-sa-mb-dades-pati",
      "slug": "mb-dades-pati",
      "url": "situacio/index.html?id=mb-dades-pati",
      "titol": "Dades que parlen del pati",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "dades",
      "tematicaLabel": "Observació i dades responsables",
      "materia": "medi",
      "materiaLabel": "Ciències, Matemàtiques i Tecnologia",
      "sessions": "5 sessions",
      "repte": "Com podem recollir dades de l’entorn del pati i transformar-les en un prototip útil sense exposar informació personal?"
    },
    {
      "id": "situacio-sa-mb-energia-aula",
      "slug": "mb-energia-aula",
      "url": "situacio/index.html?id=mb-energia-aula",
      "titol": "La llum que usem",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Energia i dades del centre",
      "materia": "medi",
      "materiaLabel": "Ciències, Matemàtiques i Tecnologia",
      "sessions": "6 sessions",
      "repte": "Què ens diuen les lectures de llum sobre l’ús de la il·luminació i quina proposta podem defensar amb dades?"
    },
    {
      "id": "situacio-sa-mb-fonaments-computacio",
      "slug": "mb-fonaments-computacio",
      "url": "situacio/index.html?id=mb-fonaments-computacio",
      "titol": "Fonaments per a pensar amb ordinadors",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "programacio",
      "tematicaLabel": "Fonaments de computació",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Pensament Computacional",
      "sessions": "6 sessions",
      "repte": "Com passem d’un problema quotidià a un algorisme precís, un programa provat i una explicació de com cooperen maquinari i programari?"
    },
    {
      "id": "situacio-sa-mb-ia-exercici-responsable",
      "slug": "mb-ia-exercici-responsable",
      "url": "situacio/index.html?id=mb-ia-exercici-responsable",
      "titol": "Un temporitzador d’activitats responsable",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "innovacio",
      "tematicaLabel": "IA, moviment i disseny responsable",
      "materia": "tecnologia",
      "materiaLabel": "Ciències, Matemàtiques i Ciutadania Digital",
      "sessions": "8 sessions",
      "repte": "Com podem crear un temporitzador de maqueta amb aprenentatge automàtic i explicar amb honestedat quan falla?"
    },
    {
      "id": "situacio-sa-mb-ia-tastet",
      "slug": "mb-ia-tastet",
      "url": "situacio/index.html?id=mb-ia-tastet",
      "titol": "Primer tast d’intel·ligència artificial",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "ciutadania",
      "tematicaLabel": "Dades i intel·ligència artificial",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Ciutadania Digital",
      "sessions": "2 sessions",
      "repte": "Com podem explicar què és la IA i provar si un model reconeix dos moviments que no ha vist abans?"
    },
    {
      "id": "situacio-sa-mb-models-moviment",
      "slug": "mb-models-moviment",
      "url": "situacio/index.html?id=mb-models-moviment",
      "titol": "Una maqueta que aprén patrons",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "innovacio",
      "tematicaLabel": "Dades, models i patrimoni",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Ciències",
      "sessions": "7 sessions",
      "repte": "Com podem fer que una maqueta reconega patrons de moviment, provar-ne els errors i explicar per a qui funciona?"
    },
    {
      "id": "situacio-sa-mb-moviment-cooperatiu",
      "slug": "mb-moviment-cooperatiu",
      "url": "situacio/index.html?id=mb-moviment-cooperatiu",
      "titol": "Moviment cooperatiu i dades",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "salut",
      "tematicaLabel": "Joc, dades i benestar",
      "materia": "educacio-fisica",
      "materiaLabel": "Educació Física, Matemàtiques i Tecnologia",
      "sessions": "5 sessions",
      "repte": "Com podem crear un selector de jocs de moviment amb variables i atzar sense convertir les dades en puntuacions personals?"
    },
    {
      "id": "situacio-sa-mb-provador-conductivitat",
      "slug": "mb-provador-conductivitat",
      "url": "situacio/index.html?id=mb-provador-conductivitat",
      "titol": "Un provador de materials",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "ciencia",
      "tematicaLabel": "Materials i circuits",
      "materia": "medi",
      "materiaLabel": "Ciències, Matemàtiques i Tecnologia",
      "sessions": "5 sessions",
      "repte": "Com podem usar una entrada de micro:bit i una condició per investigar quins materials condueixen electricitat?"
    },
    {
      "id": "situacio-sa-mb-raco-lectura",
      "slug": "mb-raco-lectura",
      "url": "situacio/index.html?id=mb-raco-lectura",
      "titol": "Sis projectes per a la biblioteca",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "art",
      "tematicaLabel": "Lectura i creació digital",
      "materia": "llengua",
      "materiaLabel": "Llengua, Matemàtiques i Tecnologia",
      "sessions": "6 sessions",
      "repte": "Com podem combinar entrades, eixides, sensors i aleatorietat per crear sis projectes útils i lúdics per a la biblioteca?"
    },
    {
      "id": "situacio-sa-mb-reptes-planeta",
      "slug": "mb-reptes-planeta",
      "url": "situacio/index.html?id=mb-reptes-planeta",
      "titol": "Reptes micro:bit per a cuidar l’entorn i les persones",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Reptes de disseny amb impacte",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Ciències i Ciutadania",
      "sessions": "10–15 sessions · selecció de reptes",
      "repte": "Quin prototip podem dissenyar per a respondre a un repte real sense prometre una protecció que la tecnologia no pot garantir?"
    },
    {
      "id": "situacio-sa-mb-ritmes-pati",
      "slug": "mb-ritmes-pati",
      "url": "situacio/index.html?id=mb-ritmes-pati",
      "titol": "Ritmes del pati en codi",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "art",
      "tematicaLabel": "Música i expressió",
      "materia": "artistica",
      "materiaLabel": "Música i Tecnologia",
      "sessions": "5 sessions",
      "repte": "Com podem convertir una idea rítmica en instruccions que altres persones i la micro:bit puguen interpretar?"
    },
    {
      "id": "situacio-sa-mb-targetes-paraules",
      "slug": "mb-targetes-paraules",
      "url": "situacio/index.html?id=mb-targetes-paraules",
      "titol": "Paraules en targetes digitals",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "llengua",
      "tematicaLabel": "Vocabulari i representació",
      "materia": "llengua",
      "materiaLabel": "Llengües, Art i Tecnologia",
      "sessions": "5 sessions",
      "repte": "Com podem dissenyar una targeta digital que ajude a recordar vocabulari amb icones, seqüències i temps d’espera?"
    },
    {
      "id": "situacio-sa-mb-tecnologia-benestar",
      "slug": "mb-tecnologia-benestar",
      "url": "situacio/index.html?id=mb-tecnologia-benestar",
      "titol": "Tecnologia per al benestar quotidià",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "ciutadania",
      "tematicaLabel": "Disseny responsable i benestar",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Ciències i Ciutadania",
      "sessions": "5 sessions",
      "repte": "Com podem dissenyar una ajuda tecnològica senzilla que facilite una rutina de benestar sense vigilar ni diagnosticar ningú?"
    },
    {
      "id": "situacio-sa-mb-xifres-que-viatgen",
      "slug": "mb-xifres-que-viatgen",
      "url": "situacio/index.html?id=mb-xifres-que-viatgen",
      "titol": "Xifres que viatgen",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "historia",
      "tematicaLabel": "Missatges i patrimoni",
      "materia": "tecnologia",
      "materiaLabel": "Història, Matemàtiques i Programació",
      "sessions": "4 sessions · 200 min",
      "repte": "Com podem codificar i descodificar un missatge amb un algorisme, i quins límits té el xifrat de Cèsar?"
    },
    {
      "id": "situacio-sa-mercat-tangible",
      "slug": "mercat-tangible",
      "url": "situacio/index.html?id=mercat-tangible",
      "titol": "Ruta Saludable pel Mercat del Barri",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "salut",
      "tematicaLabel": "Salut, hàbits i benestar",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques",
      "sessions": "4 sessions",
      "repte": "Com podem planificar la compra de fruites i verdures de temporada al mercat gastant el pressupost just i fent el camí més curt?"
    },
    {
      "id": "situacio-sa-residus-lego",
      "slug": "residus-lego",
      "url": "situacio/index.html?id=residus-lego",
      "titol": "Què pot saber un sensor de color?",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Residus, consum i sostenibilitat",
      "materia": "medi",
      "materiaLabel": "Coneixement del Medi, Ciències i Tecnologia",
      "sessions": "5 sessions",
      "repte": "Podem crear una màquina que classifique mostres de prova i explicar amb honestedat què no sap identificar?"
    },
    {
      "id": "situacio-sa-sp-ajudant-receptes",
      "slug": "sp-ajudant-receptes",
      "url": "situacio/index.html?id=sp-ajudant-receptes",
      "titol": "Un ajudant de receptes en maqueta",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "salut",
      "tematicaLabel": "Alimentació i vida quotidiana",
      "materia": "medi",
      "materiaLabel": "Coneixement del Medi, Matemàtiques i Tecnologia",
      "sessions": "5 sessions · 250 min",
      "repte": "Com podem prototipar un ajudant mecànic per a una tasca de cuina i fer que siga fàcil i segur d’utilitzar?"
    },
    {
      "id": "situacio-sa-sp-benvinguda",
      "slug": "sp-benvinguda",
      "url": "situacio/index.html?id=sp-benvinguda",
      "titol": "Una benvinguda amb moviment",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "societat",
      "tematicaLabel": "Acollida i convivència",
      "materia": "llengua",
      "materiaLabel": "Llengua, Art i Tecnologia",
      "sessions": "5 sessions · 250 min",
      "repte": "Com podem dissenyar una màquina amb SPIKE Prime que reba les persones amb un moviment amable i fàcil d’entendre?"
    },
    {
      "id": "situacio-sa-sp-biblioteca-circulant",
      "slug": "sp-biblioteca-circulant",
      "url": "situacio/index.html?id=sp-biblioteca-circulant",
      "titol": "El centre logístic de la biblioteca",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "societat",
      "tematicaLabel": "Biblioteca i comunitat",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques, Tecnologia i Ciutadania Digital",
      "sessions": "7 sessions",
      "repte": "Com podem preparar, traçar, protegir i verificar un paquet de llibres en una maqueta sense exposar dades personals?"
    },
    {
      "id": "situacio-sa-sp-caminada-impossible",
      "slug": "sp-caminada-impossible",
      "url": "situacio/index.html?id=sp-caminada-impossible",
      "titol": "La desfilada de les caminades impossibles",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "art",
      "tematicaLabel": "Moviment i disseny",
      "materia": "medi",
      "materiaLabel": "Física, Matemàtiques i Tecnologia",
      "sessions": "5 sessions · 250 min",
      "repte": "Com podem fer avançar un model LEGO SPIKE Prime sense rodes i quins canvis de les potes n’alteren el moviment?"
    },
    {
      "id": "situacio-sa-sp-condicions-compostes",
      "slug": "sp-condicions-compostes",
      "url": "situacio/index.html?id=sp-condicions-compostes",
      "titol": "El repte de les tres pistes",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "reptes",
      "tematicaLabel": "Jocs lògics i arquitectura escolar",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques, Disseny i Orientació",
      "sessions": "5 lliçons · 7–9 sessions",
      "repte": "Com podem crear un joc de pistes que responga a una seqüència de condicions sense confondre una simulació amb una protecció real?"
    },
    {
      "id": "situacio-sa-sp-dades-pati",
      "slug": "sp-dades-pati",
      "url": "situacio/index.html?id=sp-dades-pati",
      "titol": "El pati: dades, ritme i decisions",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Pati, clima i cura de l’hort",
      "materia": "medi",
      "materiaLabel": "Ciències, Matemàtiques, Música i Tecnologia",
      "sessions": "10–12 sessions",
      "repte": "Com podem dissenyar programes amb variables i dades per a un festival escolar, comprovant la fiabilitat de cada decisió?"
    },
    {
      "id": "situacio-sa-sp-debug-rutes",
      "slug": "sp-debug-rutes",
      "url": "situacio/index.html?id=sp-debug-rutes",
      "titol": "Depurar per arribar-hi",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "depuracio",
      "tematicaLabel": "Depuració i mobilitat",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Pensament Computacional",
      "sessions": "6 lliçons · 7–10 sessions",
      "repte": "Com distingim un error de muntatge d’un error de programa i com demostrem que una ruta autònoma funciona de manera fiable?"
    },
    {
      "id": "situacio-sa-sp-disseny-iteratiu",
      "slug": "sp-disseny-iteratiu",
      "url": "situacio/index.html?id=sp-disseny-iteratiu",
      "titol": "Dissenyar, provar i compartir",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "disseny",
      "tematicaLabel": "Disseny iteratiu i comunicació",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Llengües i Emprenedoria",
      "sessions": "6 lliçons · 7–9 sessions",
      "repte": "Com transformem una idea útil en un prototip provat i en una explicació que ajude altres persones a valorar-la?"
    },
    {
      "id": "situacio-sa-sp-eines-missio-eva",
      "slug": "sp-eines-missio-eva",
      "url": "situacio/index.html?id=sp-eines-missio-eva",
      "titol": "Eines per a una missió de servei espacial",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "espai",
      "tematicaLabel": "Exploració i enginyeria espacial",
      "materia": "medi",
      "materiaLabel": "Ciències, Tecnologia i Disseny",
      "sessions": "5 sessions · 250 min",
      "repte": "Com podem dissenyar una eina que ajude una persona amb guants a moure peces o guiar un cable en una reparació simulada?"
    },
    {
      "id": "situacio-sa-sp-fonaments-fisics",
      "slug": "sp-fonaments-fisics",
      "url": "situacio/index.html?id=sp-fonaments-fisics",
      "titol": "Robots que ens ajuden",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "robotica",
      "tematicaLabel": "Computació física i professions",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Ciències i Orientació",
      "sessions": "6 lliçons · 6–8 sessions",
      "repte": "Què fa que una màquina siga un robot i com podem combinar maquinari, programa i treball en equip per resoldre una necessitat real?"
    },
    {
      "id": "situacio-sa-sp-itineraris-professionals",
      "slug": "sp-itineraris-professionals",
      "url": "situacio/index.html?id=sp-itineraris-professionals",
      "titol": "Camins, habilitats i possibilitats",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "professions",
      "tematicaLabel": "Professions i comunitat",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Orientació i Competència Digital",
      "sessions": "3 lliçons · 5–6 sessions",
      "repte": "Quines persones, competències i itineraris formatius fan possible una fira tecnològica accessible, i com podem investigar opcions sense predir el futur de ningú?"
    },
    {
      "id": "situacio-sa-sp-llistes-condicions",
      "slug": "sp-llistes-condicions",
      "url": "situacio/index.html?id=sp-llistes-condicions",
      "titol": "Lògica per a una escola oberta",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "logica",
      "tematicaLabel": "Llistes, condicions i serveis escolars",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Educació en Valors",
      "sessions": "6 lliçons · 8–10 sessions",
      "repte": "Com pot una maqueta llegir una seqüència, aplicar regles explícites i respondre a una ruta sense tractar-la com un sistema de seguretat real?"
    },
    {
      "id": "situacio-sa-sp-museu-accessible",
      "slug": "sp-museu-accessible",
      "url": "situacio/index.html?id=sp-museu-accessible",
      "titol": "Laboratori de solucions accessibles",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "societat",
      "tematicaLabel": "Disseny per a la comunitat",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Disseny i Matemàtiques",
      "sessions": "8–10 sessions",
      "repte": "Com podem identificar una necessitat, prototipar alternatives i millorar una solució accessible amb proves justes?"
    },
    {
      "id": "situacio-sa-sp-prime-combinat",
      "slug": "sp-prime-combinat",
      "url": "situacio/index.html?id=sp-prime-combinat",
      "titol": "Casa eficient i collita delicada",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Energia i agricultura de proximitat",
      "materia": "medi",
      "materiaLabel": "Ciències, Tecnologia i Matemàtiques",
      "sessions": "7–8 sessions",
      "repte": "Com podem automatitzar una acció quotidiana de menor impacte i dissenyar una eina que manege el fruit amb suavitat?"
    },
    {
      "id": "situacio-sa-sp-projecte-computacio-fisica",
      "slug": "sp-projecte-computacio-fisica",
      "url": "situacio/index.html?id=sp-projecte-computacio-fisica",
      "titol": "Un prototip per a un repte real",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "projecte",
      "tematicaLabel": "Projecte de computació física",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Ciències, Matemàtiques i Disseny",
      "sessions": "500 min · 10–12 sessions",
      "repte": "Quin problema concret de la comunitat podem investigar i representar amb un prototip SPIKE Prime, i quines proves necessitem per explicar-ne el valor i els límits?"
    },
    {
      "id": "situacio-sa-sp-proves-avaluacio",
      "slug": "sp-proves-avaluacio",
      "url": "situacio/index.html?id=sp-proves-avaluacio",
      "titol": "Provar abans de decidir",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "enginyeria",
      "tematicaLabel": "Disseny, energia i ús responsable",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Ciències, Matemàtiques i Orientació",
      "sessions": "8 lliçons · 9–12 sessions",
      "repte": "Quines proves i dades necessitem abans de dir que un prototip funciona o que un robot és millor per a una tasca?"
    },
    {
      "id": "situacio-sa-sp-python-bucles",
      "slug": "sp-python-bucles",
      "url": "situacio/index.html?id=sp-python-bucles",
      "titol": "Un mosaic de moviments repetits",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "python",
      "tematicaLabel": "Python: bucles i repetició",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques, Art i Programació",
      "sessions": "7 lliçons · 7–10 sessions",
      "repte": "Com podem programar una màquina de mosaic de taula amb patrons repetibles, controlar quantes vegades actua i evitar que un bucle continue quan ja ha acabat la tasca?"
    },
    {
      "id": "situacio-sa-sp-python-comunicacio",
      "slug": "sp-python-comunicacio",
      "url": "situacio/index.html?id=sp-python-comunicacio",
      "titol": "Missatges que arriben",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "python",
      "tematicaLabel": "Python: maquinari, programari i comunicació",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Llengües i Programació",
      "sessions": "6 lliçons oficials + 1 ampliació · 7–9 sessions",
      "repte": "Com podem crear un senyal escolar inclusiu amb Python, llum i so, i comprovar que el missatge s’entén en diferents condicions d’ús?"
    },
    {
      "id": "situacio-sa-sp-python-condicions",
      "slug": "sp-python-condicions",
      "url": "situacio/index.html?id=sp-python-condicions",
      "titol": "Una decisió, dues comprovacions",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "python",
      "tematicaLabel": "Python: condicions i seguretat digital",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Programació",
      "sessions": "6 lliçons · 6–8 sessions",
      "repte": "Com podem combinar comprovacions en Python per decidir quan una maqueta de préstec de material pot mostrar una resposta, i com provem que no confon casos?"
    },
    {
      "id": "situacio-sa-sp-python-dades",
      "slug": "sp-python-dades",
      "url": "situacio/index.html?id=sp-python-dades",
      "titol": "Dades que orienten el trajecte",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "python",
      "tematicaLabel": "Python, dades i mobilitat escolar",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Ciències Socials",
      "sessions": "7 lliçons · 7–10 sessions",
      "repte": "Com podem recollir dades amb sensors SPIKE, comprovar-les i usar càlculs en Python per planificar un trajecte simulat de manera comprensible?"
    },
    {
      "id": "situacio-sa-sp-python-depuracio",
      "slug": "sp-python-depuracio",
      "url": "situacio/index.html?id=sp-python-depuracio",
      "titol": "Python: el laboratori de depuració",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "python",
      "tematicaLabel": "Python i depuració de prototips",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Programació",
      "sessions": "6 lliçons · 5–6 sessions",
      "repte": "Com podem localitzar si un comportament inesperat prové del disseny, d’una connexió, d’un error de sintaxi o de la lògica del programa Python?"
    },
    {
      "id": "situacio-sa-sp-python-funcions",
      "slug": "sp-python-funcions",
      "url": "situacio/index.html?id=sp-python-funcions",
      "titol": "Funcions que fan equip",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "python",
      "tematicaLabel": "Python: funcions i paràmetres",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Programació",
      "sessions": "6 lliçons · 6–8 sessions",
      "repte": "Com podem dividir el triatge d’una jornada escolar en accions reutilitzables i ensenyar un prototip SPIKE a executar-les amb dades diferents?"
    },
    {
      "id": "situacio-sa-sp-python-jocs",
      "slug": "sp-python-jocs",
      "url": "situacio/index.html?id=sp-python-jocs",
      "titol": "Fira de jocs amb regles clares",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "python",
      "tematicaLabel": "Python: condicions simples i jocs",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Programació",
      "sessions": "8 lliçons · 8–12 sessions",
      "repte": "Com podem crear un joc de fira amb regles transparents en què una condició Python canvie una resposta del model, el marcador siga fiable i tothom puga participar?"
    },
    {
      "id": "situacio-sa-sp-python-llistes",
      "slug": "sp-python-llistes",
      "url": "situacio/index.html?id=sp-python-llistes",
      "titol": "Paraules en llista, històries en ruta",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "python",
      "tematicaLabel": "Python: llistes i joc de paraules",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Llengües i Programació",
      "sessions": "6 lliçons · 8–12 sessions",
      "repte": "Com pot una llista Python organitzar dades en ordre, comparar col·leccions i convertir senyals de color en peces d’una història col·laborativa?"
    },
    {
      "id": "situacio-sa-sp-python-motors",
      "slug": "sp-python-motors",
      "url": "situacio/index.html?id=sp-python-motors",
      "titol": "Moviment amb motiu",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "python",
      "tematicaLabel": "Python: motors, posició i automatització",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Programació",
      "sessions": "6 lliçons · 6–8 sessions",
      "repte": "Com podem programar un mecanisme SPIKE que complete moviments útils i repetibles en una ruta de transport simulada, i demostrar-ne la precisió amb proves?"
    },
    {
      "id": "situacio-sa-sp-python-projecte-transport",
      "slug": "sp-python-projecte-transport",
      "url": "situacio/index.html?id=sp-python-projecte-transport",
      "titol": "Un trajecte útil, un prototip que aprén",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "python",
      "tematicaLabel": "Projecte culminant: transport i Python",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Programació",
      "sessions": "10 lliçons · 10–14 sessions",
      "repte": "Com podem dissenyar i programar en Python un prototip SPIKE que transporte materials de maqueta per una ruta escolar definida, i comunicar amb dades què resol i què encara no?"
    },
    {
      "id": "situacio-sa-sp-python-sensors",
      "slug": "sp-python-sensors",
      "url": "situacio/index.html?id=sp-python-sensors",
      "titol": "Una parada a temps",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "python",
      "tematicaLabel": "Python: sensors i decisions",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Ciències i Programació",
      "sessions": "6 lliçons · 6–8 sessions",
      "repte": "Com podem fer que un prototip SPIKE prime una ordre amb sensor de força, reconega una zona d’aturada amb distància i transporte una càrrega lleugera sense eixir del recorregut?"
    },
    {
      "id": "situacio-sa-sp-rampa-dades",
      "slug": "sp-rampa-dades",
      "url": "situacio/index.html?id=sp-rampa-dades",
      "titol": "Energia en una pista de proves",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Moviment i energia",
      "materia": "medi",
      "materiaLabel": "Ciències, Matemàtiques i Tecnologia",
      "sessions": "6 sessions",
      "repte": "Què podem inferir sobre energia i moviment amb un vehicle de maqueta, i com descrivim l’error de les nostres mesures?"
    },
    {
      "id": "situacio-sa-sp-reg-hort",
      "slug": "sp-reg-hort",
      "url": "situacio/index.html?id=sp-reg-hort",
      "titol": "Un indicador de reg per a l’hort escolar",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Agricultura i dades meteorològiques",
      "materia": "medi",
      "materiaLabel": "Ciències, Matemàtiques i Tecnologia",
      "sessions": "3 sessions de 45–60 min",
      "repte": "Com podem transformar la previsió de pluja d’una setmana en un indicador calibrat i útil per a prendre una decisió sobre una maqueta d’hort?"
    },
    {
      "id": "situacio-sa-sp-reptes-cooperatius",
      "slug": "sp-reptes-cooperatius",
      "url": "situacio/index.html?id=sp-reptes-cooperatius",
      "titol": "Reptes cooperatius de taller",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "societat",
      "tematicaLabel": "Cooperació i creativitat",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Llengua",
      "sessions": "5 sessions",
      "repte": "Com podem generar idees, explicar per a què serveixen i convertir-les en un repte mecànic cooperatiu?"
    },
    {
      "id": "situacio-sa-sp-sensors-logistica",
      "slug": "sp-sensors-logistica",
      "url": "situacio/index.html?id=sp-sensors-logistica",
      "titol": "Sensors al servei de la biblioteca",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "logistica",
      "tematicaLabel": "Sensors i logística escolar",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Ciències Socials",
      "sessions": "8 lliçons · 10–14 sessions",
      "repte": "Com pot un robot detectar condicions, actuar amb seguretat i coordinar-se amb altres equips sense confondre la simulació amb un servei real?"
    },
    {
      "id": "situacio-sa-sp-titelles-moviment",
      "slug": "sp-titelles-moviment",
      "url": "situacio/index.html?id=sp-titelles-moviment",
      "titol": "Titelles mecàniques de l’Albufera",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "art",
      "tematicaLabel": "Relat, natura i expressió",
      "materia": "artistica",
      "materiaLabel": "Educació Artística, Llengua i Tecnologia",
      "sessions": "5 sessions · 250 min",
      "repte": "Com podem transformar el gir d’un motor en el moviment expressiu d’una titella que conta una història local?"
    },
    {
      "id": "situacio-sa-sp-variables-distancia",
      "slug": "sp-variables-distancia",
      "url": "situacio/index.html?id=sp-variables-distancia",
      "titol": "Mesurar per decidir",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "dades",
      "tematicaLabel": "Variables, mesures i gestió",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Economia",
      "sessions": "6 lliçons · 7–9 sessions",
      "repte": "Com fem servir variables i mesures repetibles per a decidir quina ruta de servei escolar convé en una maqueta?"
    },
    {
      "id": "situacio-sa-sp-vent-model",
      "slug": "sp-vent-model",
      "url": "situacio/index.html?id=sp-vent-model",
      "titol": "Un indicador per a llegir dades de vent",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Meteorologia i dades",
      "materia": "medi",
      "materiaLabel": "Ciències, Matemàtiques i Tecnologia",
      "sessions": "3 sessions de 45–60 min",
      "repte": "Com podem convertir la velocitat prevista del vent en una representació calibrada, comparable i comprensible?"
    },
    {
      "id": "situacio-sa-tale-bot-biblioteca-barri",
      "slug": "tale-bot-biblioteca-barri",
      "url": "situacio/index.html?id=tale-bot-biblioteca-barri",
      "titol": "Una ruta de contes per la biblioteca",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "societat",
      "tematicaLabel": "Convivència i ciutadania",
      "materia": "llengua",
      "materiaLabel": "Llengua i Literatura",
      "sessions": "3 sessions",
      "repte": "Quina ruta pot seguir el robot per visitar tres espais de lectura, i com podem inventar una història diferent en cada parada?"
    },
    {
      "id": "situacio-sa-tale-bot-cami-llavors",
      "slug": "tale-bot-cami-llavors",
      "url": "situacio/index.html?id=tale-bot-cami-llavors",
      "titol": "El camí de les llavors",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot Pro",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Hort escolar i sostenibilitat",
      "materia": "medi",
      "materiaLabel": "Descoberta de l’entorn, llenguatge i matemàtiques",
      "sessions": "4 sessions",
      "repte": "Com podem preparar una ruta per a cada llavor de paper i contar què necessitarà la planta quan comence a créixer?"
    },
    {
      "id": "situacio-sa-tale-bot-dibuix-pati",
      "slug": "tale-bot-dibuix-pati",
      "url": "situacio/index.html?id=tale-bot-dibuix-pati",
      "titol": "Dibuixem un pati que convida a jugar",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "ciutat",
      "tematicaLabel": "Ciutat intel·ligent i accessibilitat",
      "materia": "artistica",
      "materiaLabel": "Educació Artística",
      "sessions": "4 sessions de 20–25 minuts",
      "repte": "Quines formes i espais podem representar perquè el plànol del pati siga fàcil d’entendre i permeta més d’una manera de jugar?"
    },
    {
      "id": "situacio-sa-tale-bot-mapa-sonor",
      "slug": "tale-bot-mapa-sonor",
      "url": "situacio/index.html?id=tale-bot-mapa-sonor",
      "titol": "El mapa sonor del barri",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "societat",
      "tematicaLabel": "Convivència i ciutadania",
      "materia": "llengua",
      "materiaLabel": "Llengua i Literatura",
      "sessions": "4 sessions de 20–25 minuts",
      "repte": "Com podem representar sons i veus d’un barri imaginari sense confondre el mapa amb una gravació real del nostre entorn?"
    },
    {
      "id": "situacio-sa-tb-carrers-amables",
      "slug": "tb-carrers-amables",
      "url": "situacio/index.html?id=tb-carrers-amables",
      "titol": "Un barri que es mou amb cura",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot Pro",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "societat",
      "tematicaLabel": "Mobilitat i convivència",
      "materia": "medi",
      "materiaLabel": "Medi, Matemàtiques i Pensament Computacional",
      "sessions": "4 sessions",
      "repte": "Com podem traçar un recorregut pel barri que siga fàcil de seguir, segur i còmode per a diferents persones?"
    },
    {
      "id": "situacio-sa-tb-escola-descobertes",
      "slug": "tb-escola-descobertes",
      "url": "situacio/index.html?id=tb-escola-descobertes",
      "titol": "La fira de descobertes de l'escola",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "comunitat",
      "tematicaLabel": "Escola i barri",
      "materia": "medi",
      "materiaLabel": "Coneixement del Medi, Matemàtiques, Llenguatge i Educació Artística",
      "sessions": "8 sessions",
      "repte": "Com podem preparar una fira on cada ruta del robot convide a observar, comptar, conversar i crear?"
    },
    {
      "id": "situacio-sa-tb-explora-el-barri",
      "slug": "tb-explora-el-barri",
      "url": "situacio/index.html?id=tb-explora-el-barri",
      "titol": "Explorem el barri amb Tale-Bot",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "entorn",
      "tematicaLabel": "Exploració de l’entorn",
      "materia": "pensament-computacional",
      "materiaLabel": "Ciències, Matemàtiques, Llenguatge i Art",
      "sessions": "15 activitats",
      "repte": "Com podem utilitzar una ruta programada per a observar, ordenar i contar històries sobre el nostre entorn?"
    },
    {
      "id": "situacio-sa-tb-missions-comunitat",
      "slug": "tb-missions-comunitat",
      "url": "situacio/index.html?id=tb-missions-comunitat",
      "titol": "Missions de comunitat amb Tale-Bot",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "entorn",
      "tematicaLabel": "Relats i serveis comunitaris",
      "materia": "pensament-computacional",
      "materiaLabel": "Llenguatge, Medi Social i Pensament Computacional",
      "sessions": "10 activitats",
      "repte": "Com organitzem un recorregut que visite diversos llocs i conte una història que el grup puga canviar?"
    },
    {
      "id": "situacio-sa-tb-ordres-en-accio",
      "slug": "tb-ordres-en-accio",
      "url": "situacio/index.html?id=tb-ordres-en-accio",
      "titol": "Ordres en acció amb Tale-Bot",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "programacio",
      "tematicaLabel": "Seqüències i instruccions",
      "materia": "pensament-computacional",
      "materiaLabel": "Pensament computacional, Llenguatge i Matemàtiques",
      "sessions": "10 activitats breus",
      "repte": "Com podem donar instruccions clares perquè Tale-Bot arribe, salude, dance i complete una missió?"
    },
    {
      "id": "situacio-sa-tb-patrons-en-ruta",
      "slug": "tb-patrons-en-ruta",
      "url": "situacio/index.html?id=tb-patrons-en-ruta",
      "titol": "Patrons en ruta amb Tale-Bot",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "programacio",
      "tematicaLabel": "Patrons i repetició",
      "materia": "pensament-computacional",
      "materiaLabel": "Matemàtiques, Música i Pensament Computacional",
      "sessions": "7 reptes",
      "repte": "Quina part d’una ruta es repeteix i com podem expressar-la amb menys ordres sense perdre precisió?"
    },
    {
      "id": "situacio-sa-tb-rastre-corral",
      "slug": "tb-rastre-corral",
      "url": "situacio/index.html?id=tb-rastre-corral",
      "titol": "El rastre del corral",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot Pro",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "entorn",
      "tematicaLabel": "Animals i entorn",
      "materia": "pensament-computacional",
      "materiaLabel": "Descoberta de l’entorn i Pensament Computacional",
      "sessions": "3 sessions",
      "repte": "Com podem preparar un mapa amb files, columnes i una orientació inicial perquè Tale-Bot trobe cinc animals amb ordres cap avant que puguem comptar i comprovar?"
    },
    {
      "id": "situacio-sa-tren-transport",
      "slug": "tren-transport",
      "url": "situacio/index.html?id=tren-transport",
      "titol": "La línia verda: un tren per al barri",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Medi ambient i sostenibilitat",
      "materia": "medi",
      "materiaLabel": "Coneixement del medi",
      "sessions": "4 sessions de 35–40 minuts",
      "repte": "Com podem connectar l'horta, el mercat i l'escola amb un recorregut que el tren puga completar i que totes les persones entenguen?"
    }
  ],
  "tutorials": [
    {
      "id": "tutorial-ce-app-musica-distancia",
      "slug": "ce-app-musica-distancia",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "url": "tutorial/index.html?id=ce-app-musica-distancia",
      "imatge": "_assets/tutorials/ce-app-musica-distancia.webp",
      "titol": "Coding Express: app, melodies i distàncies",
      "dificultat": "Intermedi",
      "durada": "50 min",
      "descripcio": "Personalitzar les respostes dels maons d’acció amb l’app, compondre una seqüència sonora i comparar distàncies en una via."
    },
    {
      "id": "tutorial-ce-bifurcacions",
      "slug": "ce-bifurcacions",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "url": "tutorial/index.html?id=ce-bifurcacions",
      "imatge": "_assets/tutorials/ce-bifurcacions.png",
      "titol": "Canvis d'agulla i bifurcacions en Y",
      "dificultat": "Intermedi",
      "durada": "45 min",
      "descripcio": "Utilitzar peces de canvi de via per crear rutes alternatives i prendre decisions de transport segons"
    },
    {
      "id": "tutorial-ce-bucles",
      "slug": "ce-bucles",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "url": "tutorial/index.html?id=ce-bucles",
      "imatge": "_assets/tutorials/ce-bucles.png",
      "titol": "El bucle ferroviari: repetir un recorregut",
      "dificultat": "Iniciació",
      "durada": "40 min",
      "descripcio": "Explorar la repetició amb una via tancada, fer prediccions i comparar el bucle físic amb una seqüència d’accions."
    },
    {
      "id": "tutorial-ce-motors-sensors",
      "slug": "ce-motors-sensors",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "url": "tutorial/index.html?id=ce-motors-sensors",
      "imatge": "_assets/tutorials/ce-motors-sensors.png",
      "titol": "Motors i sensors: Els maons d'acció de colors",
      "dificultat": "Iniciació",
      "durada": "45 min",
      "descripcio": "Descobrir la relació causa-efecte col·locant els 5 maons de colors a les vies per activar sensors,"
    },
    {
      "id": "tutorial-ce-primeres-passes",
      "slug": "ce-primeres-passes",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "url": "tutorial/index.html?id=ce-primeres-passes",
      "imatge": "_assets/tutorials/ce-primeres-passes.png",
      "titol": "Primeres passes: El circuit bàsic i el motor Push & Go",
      "dificultat": "Iniciació",
      "durada": "30 min",
      "descripcio": "Com encendre la locomotora, comprendre la mecànica 'empeny per arrencar i atura amb la mà' i muntar"
    },
    {
      "id": "tutorial-cr-giroscopi-ir-control",
      "slug": "cr-giroscopi-ir-control",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "url": "tutorial/index.html?id=cr-giroscopi-ir-control",
      "imatge": "_assets/tutorials/cr-giroscopi-ir-control.webp",
      "titol": "Codey Rocky: giroscopi, control i comunicació infraroja",
      "dificultat": "Avançat",
      "durada": "60 min",
      "descripcio": "Llegir la inclinació i el potenciòmetre, usar l’altaveu i enviar un senyal IR entre robots Codey Rocky."
    },
    {
      "id": "tutorial-cr-motors-sensors",
      "slug": "cr-motors-sensors",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "url": "tutorial/index.html?id=cr-motors-sensors",
      "imatge": "_assets/tutorials/cr-motors-sensors.png",
      "titol": "Motors i sensors: Esquivador d'obstacles amb infrarojos",
      "dificultat": "Intermedi",
      "durada": "45 min",
      "descripcio": "Utilitzar les erugues de Rocky i el sensor frontal per aturar-se o girar abans de xocar contra una"
    },
    {
      "id": "tutorial-cr-primeres-passes",
      "slug": "cr-primeres-passes",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "url": "tutorial/index.html?id=cr-primeres-passes",
      "imatge": "_assets/tutorials/cr-primeres-passes.png",
      "titol": "Primeres passes: Connexió a mBlock 5 i cares a la matriu LED",
      "dificultat": "Iniciació",
      "durada": "35 min",
      "descripcio": "Connectar Codey al software de l'ordinador o tauleta i programar animacions facials i missatges lliscants."
    },
    {
      "id": "tutorial-cr-sensors-llum-so-linia",
      "slug": "cr-sensors-llum-so-linia",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "url": "tutorial/index.html?id=cr-sensors-llum-so-linia",
      "imatge": "_assets/tutorials/cr-sensors-llum-so-linia.webp",
      "titol": "Codey Rocky: llum, so, RGB i seguiment de línia",
      "dificultat": "Intermedi",
      "durada": "55 min",
      "descripcio": "Explorar els sensors de llum, so i infraroig/color i combinar-los amb l’indicador RGB i els motors de Rocky."
    },
    {
      "id": "tutorial-cr-veu-ia",
      "slug": "cr-veu-ia",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "url": "tutorial/index.html?id=cr-veu-ia",
      "imatge": "_assets/tutorials/cr-veu-ia.png",
      "titol": "Reconeixement de veu i Intel·ligència Artificial",
      "dificultat": "Avançat",
      "durada": "50 min",
      "descripcio": "Utilitzar l'extensió de Serveis Cognitius per controlar el moviment del robot mitjançant ordres de"
    },
    {
      "id": "tutorial-cs-bucles",
      "slug": "cs-bucles",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "url": "tutorial/index.html?id=cs-bucles",
      "imatge": "_assets/tutorials/cs-bucles.png",
      "titol": "Bucles de repetició i estructures de control",
      "dificultat": "Intermedi",
      "durada": "45 min",
      "descripcio": "Empaquetar conjunts d'instruccions dins de blocs de bucle per crear figures regulars i camins repetitius."
    },
    {
      "id": "tutorial-cs-funcions-blocs-divertits",
      "slug": "cs-funcions-blocs-divertits",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "url": "tutorial/index.html?id=cs-funcions-blocs-divertits",
      "imatge": "_assets/tutorials/cs-funcions-fun-blocks.webp",
      "titol": "Coding Set: funcions i blocs divertits",
      "dificultat": "Intermedi",
      "durada": "45 min",
      "descripcio": "Definir i cridar una funció amb blocs físics i explorar moviment aleatori, música predefinida i dansa del MatataBot."
    },
    {
      "id": "tutorial-cs-motors-sensors",
      "slug": "cs-motors-sensors",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "url": "tutorial/index.html?id=cs-motors-sensors",
      "imatge": "_assets/tutorials/cs-motors-sensors.png",
      "titol": "Motors i paràmetres numèrics",
      "dificultat": "Intermedi",
      "durada": "40 min",
      "descripcio": "Optimitzar el codi combinant les fitxes direccionals amb blocs de números (1, 2, 3, 4, 5) per estalviar"
    },
    {
      "id": "tutorial-cs-primeres-passes",
      "slug": "cs-primeres-passes",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "url": "tutorial/index.html?id=cs-primeres-passes",
      "imatge": "_assets/tutorials/cs-primeres-passes.png",
      "titol": "Primeres passes: La torre de lectura i el tauler físic",
      "dificultat": "Iniciació",
      "durada": "30 min",
      "descripcio": "Descobrir la connexió entre la torre d'escaneig i el MatataBot, i l'ordre seqüencial d'esquerra a dreta."
    },
    {
      "id": "tutorial-mb-brujola-temperatura-bluetooth",
      "slug": "mb-brujola-temperatura-bluetooth",
      "robot": "microbit",
      "robotLabel": "Micro:bit",
      "url": "tutorial/index.html?id=mb-brujola-temperatura-bluetooth",
      "imatge": "_assets/tutorials/mb-compass-temperatura-touch-bluetooth.webp",
      "titol": "Micro:bit: brúixola, temperatura, tacte i Bluetooth",
      "dificultat": "Intermedi",
      "durada": "50 min",
      "descripcio": "Llegir el rumb i la temperatura aproximada, provar el logotip tàctil de V2 i distingir Bluetooth de ràdio."
    },
    {
      "id": "tutorial-mb-fanalet-llum",
      "slug": "mb-fanalet-llum",
      "robot": "microbit",
      "robotLabel": "Micro:bit",
      "url": "tutorial/index.html?id=mb-fanalet-llum",
      "imatge": "_assets/tutorials/mb-fanalet-llum.png",
      "titol": "micro:bit: un fanalet que respon a la llum",
      "dificultat": "Iniciació",
      "durada": "35 min",
      "descripcio": "Llegir la llum ambiental amb la matriu LED i encendre una icona quan l’entorn s’enfosqueix."
    },
    {
      "id": "tutorial-mb-motors-sensors",
      "slug": "mb-motors-sensors",
      "robot": "microbit",
      "robotLabel": "Micro:bit",
      "url": "tutorial/index.html?id=mb-motors-sensors",
      "imatge": "_assets/tutorials/mb-motors-sensors.png",
      "titol": "Motors i sensors: Sensor d'humitat i servomotors",
      "dificultat": "Intermedi",
      "durada": "50 min",
      "descripcio": "Connectar sensors externs als pins de la vora (P0, P1, P2) amb pinces de cocodril per automatitzar"
    },
    {
      "id": "tutorial-mb-primeres-passes",
      "slug": "mb-primeres-passes",
      "robot": "microbit",
      "robotLabel": "Micro:bit",
      "url": "tutorial/index.html?id=mb-primeres-passes",
      "imatge": "_assets/tutorials/mb-primeres-passes.png",
      "titol": "Primeres passes: MakeCode, matriu de 25 LEDs i polsadors",
      "dificultat": "Iniciació",
      "durada": "30 min",
      "descripcio": "Com programar la placa des del navegador web MakeCode sense instal·lar cap programa i descarregar l'arxiu"
    },
    {
      "id": "tutorial-mb-radio-mesh",
      "slug": "mb-radio-mesh",
      "robot": "microbit",
      "robotLabel": "Micro:bit",
      "url": "tutorial/index.html?id=mb-radio-mesh",
      "imatge": "_assets/tutorials/mb-radio-mesh.png",
      "titol": "Xarxa de ràdio sense fils: Walkie-talkie i sensors remots",
      "dificultat": "Intermedi",
      "durada": "45 min",
      "descripcio": "Connectar diverses micro:bits de l'aula entre si utilitzant l'antena de ràdio integrada sense necessitat"
    },
    {
      "id": "tutorial-mb-so-microfon",
      "slug": "mb-so-microfon",
      "robot": "microbit",
      "robotLabel": "Micro:bit",
      "url": "tutorial/index.html?id=mb-so-microfon",
      "imatge": "_assets/tutorials/mb-so-microfon.png",
      "titol": "Micròfon i so: Detector de soroll i aplaudiments (V2)",
      "dificultat": "Iniciació",
      "durada": "35 min",
      "descripcio": "Utilitzar el micròfon MEMS de la versió 2 per controlar el nivell de decibels de l'aula o encendre"
    },
    {
      "id": "tutorial-sp-brac-sensor-forca",
      "slug": "sp-brac-sensor-forca",
      "robot": "spike",
      "robotLabel": "Spike",
      "url": "tutorial/index.html?id=sp-brac-sensor-forca",
      "imatge": "_assets/tutorials/sp-brac-sensor-forca.png",
      "titol": "Braç robòtic i sensor de força",
      "dificultat": "Avançat",
      "durada": "55 min",
      "descripcio": "Construir una pinça que detecti el contacte i utilitzar les lectures del sensor de força per provar"
    },
    {
      "id": "tutorial-sp-distancia",
      "slug": "sp-distancia",
      "robot": "spike",
      "robotLabel": "Spike",
      "url": "tutorial/index.html?id=sp-distancia",
      "imatge": "_assets/tutorials/sp-distancia.png",
      "titol": "SPIKE Prime: calcular una parada sense tocar l’obstacle",
      "dificultat": "Intermedi",
      "durada": "45 min",
      "descripcio": "Ajustar el recorregut d’una base motriu amb girs de roda i comparar el càlcul amb una parada per contacte."
    },
    {
      "id": "tutorial-sp-motors-sensors",
      "slug": "sp-motors-sensors",
      "robot": "spike",
      "robotLabel": "Spike",
      "url": "tutorial/index.html?id=sp-motors-sensors",
      "imatge": "_assets/tutorials/sp-motors-sensors.png",
      "titol": "Motors i sensors: Tren d'engranatges i sensor de color",
      "dificultat": "Intermedi",
      "durada": "50 min",
      "descripcio": "Muntar un vehicle amb reductora d'engranatges per guanyar força i aturar-lo exactament davant d'una"
    },
    {
      "id": "tutorial-sp-primeres-passes",
      "slug": "sp-primeres-passes",
      "robot": "spike",
      "robotLabel": "Spike",
      "url": "tutorial/index.html?id=sp-primeres-passes",
      "imatge": "_assets/tutorials/sp-primeres-passes.png",
      "titol": "Primeres passes: El Hub intel·ligent i el primer programa",
      "dificultat": "Iniciació",
      "durada": "35 min",
      "descripcio": "Connexió del Hub per Bluetooth a l'App SPIKE, gestió de la matriu 5x5 de LEDs i bateria recarregable."
    },
    {
      "id": "tutorial-sp-sensor-distancia-alarma",
      "slug": "sp-sensor-distancia-alarma",
      "robot": "spike",
      "robotLabel": "Spike",
      "url": "tutorial/index.html?id=sp-sensor-distancia-alarma",
      "imatge": "_assets/tutorials/sp-sensor-distancia-alarma.webp",
      "titol": "SPIKE Prime: sensor de distància, giroscopi i avisador",
      "dificultat": "Intermedi",
      "durada": "55 min",
      "descripcio": "Programar una parada basada en ultrasons, mesurar un gir amb el giroscopi i fer sonar l’altaveu del Hub."
    },
    {
      "id": "tutorial-tb-motors-sensors",
      "slug": "tb-motors-sensors",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "url": "tutorial/index.html?id=tb-motors-sensors",
      "imatge": "_assets/tutorials/tb-motors-sensors.png",
      "titol": "Motors i sensors: Dibuix geomètric amb retoladors",
      "dificultat": "Intermedi",
      "durada": "45 min",
      "descripcio": "Inserir dos retoladors a les ales de TaleBot per traçar formes geomètriques de colors exactes sobre"
    },
    {
      "id": "tutorial-tb-primeres-passes",
      "slug": "tb-primeres-passes",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "url": "tutorial/index.html?id=tb-primeres-passes",
      "imatge": "_assets/tutorials/tb-primeres-passes.png",
      "titol": "Primeres passes: Botons direccionals i la tecla Delete",
      "dificultat": "Iniciació",
      "durada": "30 min",
      "descripcio": "Descobrir els comandaments bàsics de TaleBot, la mesura del seu pas (10 cm) i la importància de buidar"
    },
    {
      "id": "tutorial-tb-reconeixement-veu",
      "slug": "tb-reconeixement-veu",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "url": "tutorial/index.html?id=tb-reconeixement-veu",
      "imatge": "_assets/tutorials/tb-reconeixement-veu.png",
      "titol": "Gravació i reproducció de veu",
      "dificultat": "Iniciació",
      "durada": "40 min",
      "descripcio": "Gravar pistes d'àudio i diàlegs personalitzats amb la veu de l'alumnat a cada etapa del recorregut."
    },
    {
      "id": "tutorial-tb-repeticio-mapes-dansa",
      "slug": "tb-repeticio-mapes-dansa",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "url": "tutorial/index.html?id=tb-repeticio-mapes-dansa",
      "imatge": "_assets/tutorials/tb-repeticio-mapes-dansa.webp",
      "titol": "Tale-Bot Pro: repetició, dansa i mapes interactius",
      "dificultat": "Intermedi",
      "durada": "50 min",
      "descripcio": "Provar els comandaments de repetició i dansa, escoltar la guia OID del mapa i depurar una seqüència sense confondre gravació amb reconeixement de parla."
    }
  ],
  "robots": [
    {
      "id": "robot-coding-express",
      "slug": "coding-express",
      "prefix": "ce",
      "nom": "Coding Express",
      "edat": "Educació Infantil (2-5 anys)",
      "descripcio": "El tren interactiu dels colors i el pensament computacional primerenc",
      "colors": [
        "#e4242b",
        "#fec002"
      ],
      "order": 1,
      "url": "robot/index.html?id=coding-express",
      "tutorials": 5
    },
    {
      "id": "robot-tale-bot",
      "slug": "tale-bot",
      "prefix": "tb",
      "nom": "Tale-Bot",
      "edat": "Educació Infantil i primer cicle (3-7 anys)",
      "descripcio": "El robot narrador que parla, llegeix mapes interactius i dibuixa",
      "colors": [
        "#fc8439",
        "#804cbd"
      ],
      "order": 2,
      "url": "robot/index.html?id=tale-bot",
      "tutorials": 4
    },
    {
      "id": "robot-coding-set",
      "slug": "coding-set",
      "prefix": "cs",
      "nom": "Coding Set",
      "edat": "Educació Infantil i primària (4-9 anys)",
      "descripcio": "Programació tangible sense pantalles amb Matatalab",
      "colors": [
        "#fc7813",
        "#60a62d"
      ],
      "order": 3,
      "url": "robot/index.html?id=coding-set",
      "tutorials": 4
    },
    {
      "id": "robot-codey-rocky",
      "slug": "codey-rocky",
      "prefix": "cr",
      "nom": "Codey Rocky",
      "edat": "Primària (6-12 anys)",
      "descripcio": "El robot amb pantalla LED 16 × 8, sensors i moviment amb orugues",
      "colors": [
        "#0079dc",
        "#fdc80a"
      ],
      "order": 4,
      "url": "robot/index.html?id=codey-rocky",
      "tutorials": 5
    },
    {
      "id": "robot-spike",
      "slug": "spike",
      "prefix": "sp",
      "nom": "Spike",
      "edat": "Tercer cicle (10-12 anys)",
      "descripcio": "Mecatrònica, engranatges i sensors d'alta precisió de LEGO Education",
      "colors": [
        "#d82098",
        "#fddc3e"
      ],
      "order": 5,
      "url": "robot/index.html?id=spike",
      "tutorials": 5
    },
    {
      "id": "robot-microbit",
      "slug": "microbit",
      "prefix": "mb",
      "nom": "Micro:bit",
      "edat": "Segon i tercer cicle (8-12 anys)",
      "descripcio": "La placa microcontroladora per a projectes oberts i ciutadans",
      "colors": [
        "#047fdf",
        "#4a515d"
      ],
      "order": 6,
      "url": "robot/index.html?id=microbit",
      "tutorials": 6
    }
  ]
};
