// _js/cataleg.js - Dades del catàleg generades automàticament per _scripts/sync-catalog.py
// No editeu manualment aquest fitxer; s'actualitza amb el script o mitjançant el git hook.
window.CATALEG = {
  "activitats": [
    {
      "id": "activitat-bucles-coreografia",
      "slug": "bucles-coreografia",
      "url": "activitat/bucles-coreografia/index.html",
      "titol": "La Coreografia dels Bucles",
      "tag": "Bucles i Repetició",
      "cicle": "Primer, segon i tercer cicle",
      "durada": "45 min",
      "descripcio": "Repetiu una seqüència de moviments i busqueu la manera més clara d'explicar-la amb poques instruccions."
    },
    {
      "id": "activitat-condicionals-moviment",
      "slug": "condicionals-moviment",
      "url": "activitat/condicionals-moviment/index.html",
      "titol": "El joc dels condicionals: si... llavors... si no...",
      "tag": "Estructures de Control Condicional",
      "cicle": "Tots els cicles",
      "durada": "35 min",
      "descripcio": "Practiqueu les decisions amb targetes inventades i representeu què passa quan una condició és certa o falsa."
    },
    {
      "id": "activitat-criptografia-cesar",
      "slug": "criptografia-cesar",
      "url": "activitat/criptografia-cesar/index.html",
      "titol": "Missatges Secrets i Xifratge Cèsar",
      "tag": "Ciberseguretat i Criptografia",
      "cicle": "Segon i tercer cicle",
      "durada": "50 min",
      "descripcio": "Construcció d'una roda de xifratge de dos cercles concèntrics per comprendre com es protegeix la informació a Internet desplaçant les lletres de l'alfabet un nombre fix de posicions."
    },
    {
      "id": "activitat-dades-classificacio",
      "slug": "dades-classificacio",
      "url": "activitat/dades-classificacio/index.html",
      "titol": "El Museu de les Dades",
      "tag": "Dades, Classificació i Privadesa",
      "cicle": "Primer, segon i tercer cicle",
      "durada": "50 min",
      "descripcio": "Recolliu dades inventades, trieu com classificar-les i representeu-les amb una regla clara."
    },
    {
      "id": "activitat-descomposicio-receptes",
      "slug": "descomposicio-receptes",
      "url": "activitat/descomposicio-receptes/index.html",
      "titol": "Receptes amb Instruccions de Robot",
      "tag": "Descomposició i Algorismes",
      "cicle": "Primer, segon i tercer cicle",
      "durada": "50 min",
      "descripcio": "Descomposeu una tasca quotidiana en instruccions precises i proveu què passa si en canvieu l'ordre."
    },
    {
      "id": "activitat-laberint-debugging",
      "slug": "laberint-debugging",
      "url": "activitat/laberint-debugging/index.html",
      "titol": "El Laberint d'Instruccions i Detecció d'Errors",
      "tag": "Depuració (Debugging) i Seqüenciació",
      "cicle": "Educació Infantil i primer cicle",
      "durada": "40 min",
      "descripcio": "Sobre una graella gegant al terra amb fitxes de cartolina, els alumnes col·loquen targetes de fletxes per planificar un camí abans d'executar-lo. Quan troben un obstacle, aprenen a aïllar l'ordre equivocada."
    },
    {
      "id": "activitat-patrons-simetries",
      "slug": "patrons-simetries",
      "url": "activitat/patrons-simetries/index.html",
      "titol": "Detectius de Patrons i Repeticions",
      "tag": "Patrons i Abstracció",
      "cicle": "Educació Infantil, primer i segon cicle",
      "durada": "40 min",
      "descripcio": "Observeu seqüències de formes i sons, expliqueu la regla i predigueu quin element ve després."
    },
    {
      "id": "activitat-pixels-binaris",
      "slug": "pixels-binaris",
      "url": "activitat/pixels-binaris/index.html",
      "titol": "Dibuix per Píxels i Imatges Binàries",
      "tag": "Representació de Dades (Binari)",
      "cicle": "Primer i segon cicle",
      "durada": "45 min",
      "descripcio": "Com 'veu' i guarda un ordinador un dibuix? L'alumnat codifica i descodifica imatges senzilles en quadrícules utilitzant només els valors 0 (blanc) i 1 (negre)."
    },
    {
      "id": "activitat-robot-huma",
      "slug": "robot-huma",
      "url": "activitat/robot-huma/index.html",
      "titol": "El Robot Humà i el Llenguatge Precís",
      "tag": "Algorismes i Precisió",
      "cicle": "Educació Infantil i primer cicle",
      "durada": "45 min",
      "descripcio": "Una persona interpreta el robot sobre una graella, i una altra programa un recorregut amb instruccions precises i verificables."
    },
    {
      "id": "activitat-xarxa-ordenacio",
      "slug": "xarxa-ordenacio",
      "url": "activitat/xarxa-ordenacio/index.html",
      "titol": "Xarxa d'Ordenació al Terra (Sorting Networks)",
      "tag": "Algorismes de Comparació i Processament Paral·lel",
      "cicle": "Segon i tercer cicle",
      "durada": "50 min",
      "descripcio": "Dibuixem una xarxa de línies amb guix al pati. Sis alumnes amb números desordenats avancen per les línies; en cada encreuament es comparen de dos en dos i el més petit sempre va cap a l'esquerra."
    }
  ],
  "situacions": [
    {
      "id": "situacio-sa-ce-bifurcacio-parc",
      "slug": "ce-bifurcacio-parc",
      "url": "situacio/ce-bifurcacio-parc/index.html",
      "titol": "Dues rutes, una decisió",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "ciutat",
      "tematicaLabel": "Ciutat intel·ligent i accessibilitat",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques i Descoberta de l’entorn",
      "sessions": "3 sessions",
      "repte": "Quina informació ens ajuda a decidir per quina branca ha de continuar el tren i com comprovem si ha arribat al destí triat?"
    },
    {
      "id": "situacio-sa-ce-bucle-horta",
      "slug": "ce-bucle-horta",
      "url": "situacio/ce-bucle-horta/index.html",
      "titol": "El bucle de l’horta escolar",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Medi ambient i sostenibilitat",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques i Descoberta de l’entorn",
      "sessions": "3 sessions",
      "repte": "Què es repeteix quan el tren completa una volta a l’hort i com podem anticipar quantes vegades passarà pel mateix punt?"
    },
    {
      "id": "situacio-sa-ce-bucles-relats",
      "slug": "ce-bucles-relats",
      "url": "situacio/ce-bucles-relats/index.html",
      "titol": "El tren que torna",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "repeticio",
      "tematicaLabel": "Bucles i patrons que es repeteixen",
      "materia": "pensament-computacional",
      "materiaLabel": "Pensament computacional, música i llenguatge",
      "sessions": "4 sessions",
      "repte": "Com podem representar una repetició amb una ruta i explicar quan deixa de repetir-se?"
    },
    {
      "id": "situacio-sa-ce-cami-segur",
      "slug": "ce-cami-segur",
      "url": "situacio/ce-cami-segur/index.html",
      "titol": "Un camí tranquil fins a l’escola",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "ciutat",
      "tematicaLabel": "Ciutat intel·ligent i accessibilitat",
      "materia": "medi",
      "materiaLabel": "Descoberta de l’entorn",
      "sessions": "3 sessions",
      "repte": "Quines situacions poden interrompre un trajecte i com podem representar decisions prudents en una maqueta sense confondre-la amb una senyalització real?"
    },
    {
      "id": "situacio-sa-ce-concert-pati",
      "slug": "ce-concert-pati",
      "url": "situacio/ce-concert-pati/index.html",
      "titol": "Un concert de sons del pati",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "art",
      "tematicaLabel": "Art, música i expressió",
      "materia": "artistica",
      "materiaLabel": "Educació Artística i Música",
      "sessions": "3 sessions",
      "repte": "Com podem crear una seqüència sonora breu inspirada en el pati i ordenar-la perquè cada so aparega en el moment acordat?"
    },
    {
      "id": "situacio-sa-ce-distancies-estacions",
      "slug": "ce-distancies-estacions",
      "url": "situacio/ce-distancies-estacions/index.html",
      "titol": "Distàncies entre estacions",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "ciutat",
      "tematicaLabel": "Mobilitat quotidiana i orientació",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques i Descoberta de l’entorn",
      "sessions": "3 sessions",
      "repte": "Quin nombre de l’app necessita el tren per arribar a cada estació i com comprovem que ha fet el trajecte esperat?"
    },
    {
      "id": "situacio-sa-ce-habitats-albufera",
      "slug": "ce-habitats-albufera",
      "url": "situacio/ce-habitats-albufera/index.html",
      "titol": "Hàbitats vius de l’Albufera",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Biodiversitat i cura de l’entorn",
      "materia": "medi",
      "materiaLabel": "Descoberta de l’entorn, Ciències i Llenguatge",
      "sessions": "5 sessions",
      "repte": "Què necessiten els éssers vius per habitar un lloc, i com podem representar canvis que ajuden a conservar-lo?"
    },
    {
      "id": "situacio-sa-ce-missatges-estacio",
      "slug": "ce-missatges-estacio",
      "url": "situacio/ce-missatges-estacio/index.html",
      "titol": "Missatges per a l’estació",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "llengua",
      "tematicaLabel": "Llengua i comunicació",
      "materia": "llengua",
      "materiaLabel": "Llengua i Literatura",
      "sessions": "3 sessions",
      "repte": "Quina informació necessita cada estació per rebre el tren i com podem transmetre-la amb sons o símbols que tot el grup entenga?"
    },
    {
      "id": "situacio-sa-ce-oratge-pati",
      "slug": "ce-oratge-pati",
      "url": "situacio/ce-oratge-pati/index.html",
      "titol": "Un pati per a cada oratge",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "entorn",
      "tematicaLabel": "Oratge, estacions i espais de joc",
      "materia": "medi",
      "materiaLabel": "Descoberta de l’entorn, Ciències i Llenguatge",
      "sessions": "5 sessions",
      "repte": "Com podem preparar un pati acollidor per a diferents condicions d’oratge?"
    },
    {
      "id": "situacio-sa-ce-parades-emocions",
      "slug": "ce-parades-emocions",
      "url": "situacio/ce-parades-emocions/index.html",
      "titol": "Com se sent el personatge del tren?",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "societat",
      "tematicaLabel": "Convivència i ciutadania",
      "materia": "llengua",
      "materiaLabel": "Llengua i Educació emocional",
      "sessions": "3 sessions",
      "repte": "Com podem escoltar diferents interpretacions d’un personatge de ficció i representar-les sense decidir què sent una persona real?"
    },
    {
      "id": "situacio-sa-ce-primer-viatge",
      "slug": "ce-primer-viatge",
      "url": "situacio/ce-primer-viatge/index.html",
      "titol": "Explorem les peces de la via",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "societat",
      "tematicaLabel": "Convivència i ciutadania",
      "materia": "medi",
      "materiaLabel": "Descoberta de l’entorn",
      "sessions": "3 sessions",
      "repte": "Quins elements necessitem per preparar una ruta clara perquè el tren visite una estació i puga tornar al punt de partida?"
    },
    {
      "id": "situacio-sa-ce-reptes-desconnectats",
      "slug": "ce-reptes-desconnectats",
      "url": "situacio/ce-reptes-desconnectats/index.html",
      "titol": "El tren es queda al taller",
      "robot": "desendollat",
      "robotLabel": "Activitat desconnectada",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "desconnectada",
      "tematicaLabel": "Seqüències sense pantalles ni robot",
      "materia": "pensament-computacional",
      "materiaLabel": "Pensament computacional, llenguatge i matemàtiques",
      "sessions": "4 sessions",
      "repte": "Podem resoldre els mateixos reptes amb el cos, targetes i paper?"
    },
    {
      "id": "situacio-sa-ce-reptes-rutes",
      "slug": "ce-reptes-rutes",
      "url": "situacio/ce-reptes-rutes/index.html",
      "titol": "Rutes amb decisions",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "resolucio-problemes",
      "tematicaLabel": "Sistemes, rutes i resolució de problemes",
      "materia": "pensament-computacional",
      "materiaLabel": "Pensament computacional, descoberta de l’entorn i llenguatge",
      "sessions": "4 sessions",
      "repte": "Com dissenyem una ruta comprensible i la millorem quan apareix un problema?"
    },
    {
      "id": "situacio-sa-ce-sequencia-histories",
      "slug": "ce-sequencia-histories",
      "url": "situacio/ce-sequencia-histories/index.html",
      "titol": "Històries que viatgen en tren",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "narracio",
      "tematicaLabel": "Seqüències, sons i relats",
      "materia": "llengua",
      "materiaLabel": "Llenguatge, descoberta de l’entorn i pensament computacional",
      "sessions": "5 sessions",
      "repte": "Quina seqüència d’ordres permet contar una història clara amb el tren?"
    },
    {
      "id": "situacio-sa-ciutat-accessible",
      "slug": "ciutat-accessible",
      "url": "situacio/ciutat-accessible/index.html",
      "titol": "La Ciutat Accessible per a Tothom",
      "robot": "microbit",
      "robotLabel": "Micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "ciutat",
      "tematicaLabel": "Ciutat intel·ligent i accessibilitat",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia i Digitalització",
      "sessions": "6 sessions",
      "repte": "Com podem eliminar les barreres arquitectòniques i sensorials del nostre barri perquè una persona cega o amb cadira de rodes es desplaci amb seguretat?"
    },
    {
      "id": "situacio-sa-coding-set-casa-geometrica",
      "slug": "coding-set-casa-geometrica",
      "url": "situacio/coding-set-casa-geometrica/index.html",
      "titol": "Un plànol geomètric amb MatataBot",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "art",
      "tematicaLabel": "Art, música i expressió",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques",
      "sessions": "4 sessions",
      "repte": "Quantes ordres necessitem per dibuixar el contorn d’una casa i com podem simplificar el programa quan repetim moviments?"
    },
    {
      "id": "situacio-sa-coding-set-fira-matematica",
      "slug": "coding-set-fira-matematica",
      "url": "situacio/coding-set-fira-matematica/index.html",
      "titol": "La fira de formes, nombres i estrelles",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "ciencia",
      "tematicaLabel": "Ciència i entorn",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques, llengües i educació artística",
      "sessions": "5 sessions",
      "repte": "Com podem convertir les ordres de MatataBot en una fira on classifiquem formes, escrivim nombres i dibuixem constel·lacions?"
    },
    {
      "id": "situacio-sa-coding-set-futbol-cooperatiu",
      "slug": "coding-set-futbol-cooperatiu",
      "url": "situacio/coding-set-futbol-cooperatiu/index.html",
      "titol": "Un repte cooperatiu de futbol de taula",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "societat",
      "tematicaLabel": "Convivència i ciutadania",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques i Educació Física",
      "sessions": "4 sessions",
      "repte": "Com podem programar una ruta de passada perquè la pilota arribe a una zona acordada i tothom puga participar en el repte?"
    },
    {
      "id": "situacio-sa-coding-set-parc-observadors",
      "slug": "coding-set-parc-observadors",
      "url": "situacio/coding-set-parc-observadors/index.html",
      "titol": "Una ronda d’observació al parc",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Medi ambient i sostenibilitat",
      "materia": "medi",
      "materiaLabel": "Coneixement del Medi",
      "sessions": "4 sessions",
      "repte": "Com podem organitzar una ruta que visite diversos punts del parc i ens ajude a fer observacions sense molestar-ne els éssers vius?"
    },
    {
      "id": "situacio-sa-coding-set-ruta-biblioteca",
      "slug": "coding-set-ruta-biblioteca",
      "url": "situacio/coding-set-ruta-biblioteca/index.html",
      "titol": "La ruta dels llibres viatgers",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "societat",
      "tematicaLabel": "Convivència i ciutadania",
      "materia": "llengua",
      "materiaLabel": "Llengua i Literatura",
      "sessions": "4 sessions",
      "repte": "Com podem dissenyar un recorregut per portar un llibre fictici a tres espais i inventar una recomanació sense copiar cap sinopsi?"
    },
    {
      "id": "situacio-sa-conte-tale-bot",
      "slug": "conte-tale-bot",
      "url": "situacio/conte-tale-bot/index.html",
      "titol": "Els Viatges del Conte Màgic",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "art",
      "tematicaLabel": "Art, música i expressió",
      "materia": "llengua",
      "materiaLabel": "Llengua i Literatura",
      "sessions": "3 sessions",
      "repte": "Podem ajudar el protagonista del nostre conte a trobar els seus amics superant el bosc misteriós tot explicant la història amb les nostres veus?"
    },
    {
      "id": "situacio-sa-coreografia-codey",
      "slug": "coreografia-codey",
      "url": "situacio/coreografia-codey/index.html",
      "titol": "La Festa dels Autòmats: Art i Programació",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "art",
      "tematicaLabel": "Art, música i expressió",
      "materia": "artistica",
      "materiaLabel": "Educació Artística i Plàstica",
      "sessions": "4 sessions",
      "repte": "Podem sincronitzar una colla de robots perquè ballin una cançó tradicional al compàs de la música amb llums i disfresses creades per nosaltres?"
    },
    {
      "id": "situacio-sa-cr-entrades-sensors",
      "slug": "cr-entrades-sensors",
      "url": "situacio/cr-entrades-sensors/index.html",
      "titol": "El laboratori de sensors de Codey Rocky",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "tecnologia",
      "tematicaLabel": "Sensors i interacció",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Ciències",
      "sessions": "12 sessions",
      "repte": "Com pot Codey Rocky percebre senyals del seu entorn i convertir-los en respostes que siguen útils, clares i comprovables?"
    },
    {
      "id": "situacio-sa-cr-llum-aula",
      "slug": "cr-llum-aula",
      "url": "situacio/cr-llum-aula/index.html",
      "titol": "El mapa de llum de l’aula",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Medi ambient i sostenibilitat",
      "materia": "medi",
      "materiaLabel": "Coneixement del Medi / Ciències",
      "sessions": "3 sessions",
      "repte": "Com varia la lectura de llum en diferents espais de l’aula i com podem comunicar-la amb dades repetibles?"
    },
    {
      "id": "situacio-sa-cr-museu-jocs-programats",
      "slug": "cr-museu-jocs-programats",
      "url": "situacio/cr-museu-jocs-programats/index.html",
      "titol": "Museu de jocs programats",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle i ESO",
      "tematica": "programacio",
      "tematicaLabel": "Projectes interactius i robòtica",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques, Art i Pensament Computacional",
      "sessions": "24 sessions de 40 minuts",
      "repte": "Com dissenyem una exposició de jocs que es puga entendre, provar, depurar i recórrer amb Codey Rocky?"
    },
    {
      "id": "situacio-sa-cr-repartiment",
      "slug": "cr-repartiment",
      "url": "situacio/cr-repartiment/index.html",
      "titol": "Repartiment amb una ruta segura",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "ciutat",
      "tematicaLabel": "Entorn i mobilitat",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques i Tecnologia",
      "sessions": "4 sessions",
      "repte": "Com pot un vehicle programat avançar per una ruta de repartiment i reaccionar davant d’un obstacle previsible?"
    },
    {
      "id": "situacio-sa-cr-ruta-colors",
      "slug": "cr-ruta-colors",
      "url": "situacio/cr-ruta-colors/index.html",
      "titol": "Arxiu de colors de l’horta",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Medi ambient i sostenibilitat",
      "materia": "medi",
      "materiaLabel": "Coneixement del Medi / Ciències",
      "sessions": "4 sessions",
      "repte": "Com podem descriure i classificar els colors que observem a l’horta sense confondre una lectura del sensor amb la identificació d’un objecte?"
    },
    {
      "id": "situacio-sa-desendollada-cripto",
      "slug": "desendollada-cripto",
      "url": "situacio/desendollada-cripto/index.html",
      "titol": "Espies Escolars i Secrets Criptogràfics",
      "robot": "desendollat",
      "robotLabel": "Desendollat (Sense robot)",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "societat",
      "tematicaLabel": "Convivència i ciutadania digital",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques",
      "sessions": "3 sessions",
      "repte": "Com podem protegir els nostres missatges i dades privades a la xarxa perquè ningú pugui suplantar la nostra identitat?"
    },
    {
      "id": "situacio-sa-emocions-codey",
      "slug": "emocions-codey",
      "url": "situacio/emocions-codey/index.html",
      "titol": "La Mascota de les Emocions i el Benestar",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "salut",
      "tematicaLabel": "Salut, hàbits i benestar",
      "materia": "llengua",
      "materiaLabel": "Llengua i Literatura",
      "sessions": "4 sessions",
      "repte": "Com podem crear un company robòtic que ens ajudi a expressar i gestionar les nostres emocions quan estem enfadats, tristos o eufòrics?"
    },
    {
      "id": "situacio-sa-hivernacle-microbit",
      "slug": "hivernacle-microbit",
      "url": "situacio/hivernacle-microbit/index.html",
      "titol": "Alertes per al bosc i l’hort",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Biodiversitat i cultiu",
      "materia": "medi",
      "materiaLabel": "Ciències, Tecnologia i Matemàtiques",
      "sessions": "4 sessions",
      "repte": "Com podem enviar un avís de protecció i representar un sensor de cultiu sense exposar la placa a l’aigua o al sòl?"
    },
    {
      "id": "situacio-sa-laberint-mart",
      "slug": "laberint-mart",
      "url": "situacio/laberint-mart/index.html",
      "titol": "Missió de robòtica cooperativa",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "entorn",
      "tematicaLabel": "L’Albufera i la cura de l’entorn",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Ciències",
      "sessions": "12–15 sessions",
      "repte": "Com podem dissenyar un robot fiable que complete missions de cura de l’entorn i explique amb proves les decisions de l’equip?"
    },
    {
      "id": "situacio-sa-mb-animacio-volca",
      "slug": "mb-animacio-volca",
      "url": "situacio/mb-animacio-volca/index.html",
      "titol": "Una erupció en píxels",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "ciencia",
      "tematicaLabel": "Fenòmens geològics i animació",
      "materia": "medi",
      "materiaLabel": "Ciències, Geografia i Tecnologia",
      "sessions": "5 sessions",
      "repte": "Com podem descompondre un procés en fotogrames i repetir-los en una animació LED comprensible?"
    },
    {
      "id": "situacio-sa-mb-animacions-aiguamoll",
      "slug": "mb-animacions-aiguamoll",
      "url": "situacio/mb-animacions-aiguamoll/index.html",
      "titol": "Animacions de l’aiguamoll",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "natura",
      "tematicaLabel": "Natura i expressió digital",
      "materia": "artistica",
      "materiaLabel": "Educació Artística, Medi i Tecnologia",
      "sessions": "2 sessions",
      "repte": "Com podem explicar una observació de la natura amb una icona LED i una animació programada?"
    },
    {
      "id": "situacio-sa-mb-art-de-la-natura",
      "slug": "mb-art-de-la-natura",
      "url": "situacio/mb-art-de-la-natura/index.html",
      "titol": "Art de la natura en píxels",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "natura",
      "tematicaLabel": "Observació i representació",
      "materia": "artistica",
      "materiaLabel": "Educació Artística, Medi i Tecnologia",
      "sessions": "4 sessions",
      "repte": "Quins trets d’una forma natural podem conservar quan la representem primer amb materials i després amb cinc per cinc píxels?"
    },
    {
      "id": "situacio-sa-mb-aula-sensorial",
      "slug": "mb-aula-sensorial",
      "url": "situacio/mb-aula-sensorial/index.html",
      "titol": "Una aula amb opcions sensorials",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle i ESO",
      "tematica": "ciutadania",
      "tematicaLabel": "Disseny accessible",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Ciències i Inclusió",
      "sessions": "4 sessions",
      "repte": "Com podem crear un recurs visual opcional i configurable que ajude a fer més previsible una rutina de l’aula?"
    },
    {
      "id": "situacio-sa-mb-clau-segura",
      "slug": "mb-clau-segura",
      "url": "situacio/mb-clau-segura/index.html",
      "titol": "Clau segura, dades protegides",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "ciutadania",
      "tematicaLabel": "Seguretat i privacitat",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Ciutadania Digital",
      "sessions": "4 sessions",
      "repte": "Com podem explicar els riscos digitals i provar un algorisme de contrasenyes amb dades completament fictícies?"
    },
    {
      "id": "situacio-sa-mb-comptador-residus",
      "slug": "mb-comptador-residus",
      "url": "situacio/mb-comptador-residus/index.html",
      "titol": "Comptem residus amb cura",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Residus i entorn escolar",
      "materia": "medi",
      "materiaLabel": "Medi, Matemàtiques i Tecnologia",
      "sessions": "2 sessions",
      "repte": "Com podem dissenyar un comptador de micro:bit que registre residus per categoria i ens ajude a fer una proposta responsable?"
    },
    {
      "id": "situacio-sa-mb-dades-pati",
      "slug": "mb-dades-pati",
      "url": "situacio/mb-dades-pati/index.html",
      "titol": "Dades que parlen del pati",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "dades",
      "tematicaLabel": "Observació i dades responsables",
      "materia": "medi",
      "materiaLabel": "Ciències, Matemàtiques i Tecnologia",
      "sessions": "5 sessions",
      "repte": "Com podem recollir dades de l’entorn del pati i transformar-les en un prototip útil sense exposar informació personal?"
    },
    {
      "id": "situacio-sa-mb-energia-aula",
      "slug": "mb-energia-aula",
      "url": "situacio/mb-energia-aula/index.html",
      "titol": "La llum que usem",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Energia i dades del centre",
      "materia": "medi",
      "materiaLabel": "Ciències, Matemàtiques i Tecnologia",
      "sessions": "6 sessions",
      "repte": "Què ens diuen les lectures de llum sobre l’ús de la il·luminació i quina proposta podem defensar amb dades?"
    },
    {
      "id": "situacio-sa-mb-fonaments-computacio",
      "slug": "mb-fonaments-computacio",
      "url": "situacio/mb-fonaments-computacio/index.html",
      "titol": "Fonaments per a pensar amb ordinadors",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle i ESO",
      "tematica": "programacio",
      "tematicaLabel": "Fonaments de computació",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Pensament Computacional",
      "sessions": "6 sessions",
      "repte": "Com passem d’un problema quotidià a un algorisme precís, un programa provat i una explicació de com cooperen maquinari i programari?"
    },
    {
      "id": "situacio-sa-mb-ia-exercici-responsable",
      "slug": "mb-ia-exercici-responsable",
      "url": "situacio/mb-ia-exercici-responsable/index.html",
      "titol": "Un temporitzador d’activitats responsable",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "innovacio",
      "tematicaLabel": "IA, moviment i disseny responsable",
      "materia": "tecnologia",
      "materiaLabel": "Ciències, Matemàtiques i Ciutadania Digital",
      "sessions": "8 sessions",
      "repte": "Com podem crear un temporitzador de maqueta amb aprenentatge automàtic i explicar amb honestedat quan falla?"
    },
    {
      "id": "situacio-sa-mb-ia-tastet",
      "slug": "mb-ia-tastet",
      "url": "situacio/mb-ia-tastet/index.html",
      "titol": "Primer tast d’intel·ligència artificial",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "ciutadania",
      "tematicaLabel": "Dades i intel·ligència artificial",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Ciutadania Digital",
      "sessions": "2 sessions",
      "repte": "Com podem explicar què és la IA i provar si un model reconeix dos moviments que no ha vist abans?"
    },
    {
      "id": "situacio-sa-mb-models-moviment",
      "slug": "mb-models-moviment",
      "url": "situacio/mb-models-moviment/index.html",
      "titol": "Una maqueta que aprén patrons",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "innovacio",
      "tematicaLabel": "Dades, models i patrimoni",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Ciències",
      "sessions": "7 sessions",
      "repte": "Com podem fer que una maqueta reconega patrons de moviment, provar-ne els errors i explicar per a qui funciona?"
    },
    {
      "id": "situacio-sa-mb-moviment-cooperatiu",
      "slug": "mb-moviment-cooperatiu",
      "url": "situacio/mb-moviment-cooperatiu/index.html",
      "titol": "Moviment cooperatiu i dades",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "salut",
      "tematicaLabel": "Joc, dades i benestar",
      "materia": "educacio-fisica",
      "materiaLabel": "Educació Física, Matemàtiques i Tecnologia",
      "sessions": "5 sessions",
      "repte": "Com podem crear un selector de jocs de moviment amb variables i atzar sense convertir les dades en puntuacions personals?"
    },
    {
      "id": "situacio-sa-mb-provador-conductivitat",
      "slug": "mb-provador-conductivitat",
      "url": "situacio/mb-provador-conductivitat/index.html",
      "titol": "Un provador de materials",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "ciencia",
      "tematicaLabel": "Materials i circuits",
      "materia": "medi",
      "materiaLabel": "Ciències, Matemàtiques i Tecnologia",
      "sessions": "5 sessions",
      "repte": "Com podem usar una entrada de micro:bit i una condició per investigar quins materials condueixen electricitat?"
    },
    {
      "id": "situacio-sa-mb-raco-lectura",
      "slug": "mb-raco-lectura",
      "url": "situacio/mb-raco-lectura/index.html",
      "titol": "Sis projectes per a la biblioteca",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "art",
      "tematicaLabel": "Lectura i creació digital",
      "materia": "llengua",
      "materiaLabel": "Llengua, Matemàtiques i Tecnologia",
      "sessions": "6 sessions",
      "repte": "Com podem combinar entrades, eixides, sensors i aleatorietat per crear sis projectes útils i lúdics per a la biblioteca?"
    },
    {
      "id": "situacio-sa-mb-reptes-planeta",
      "slug": "mb-reptes-planeta",
      "url": "situacio/mb-reptes-planeta/index.html",
      "titol": "Reptes micro:bit per a cuidar l’entorn i les persones",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle i ESO",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Reptes de disseny amb impacte",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Ciències i Ciutadania",
      "sessions": "10–15 sessions · selecció de reptes",
      "repte": "Quin prototip podem dissenyar per a respondre a un repte real sense prometre una protecció que la tecnologia no pot garantir?"
    },
    {
      "id": "situacio-sa-mb-ritmes-pati",
      "slug": "mb-ritmes-pati",
      "url": "situacio/mb-ritmes-pati/index.html",
      "titol": "Ritmes del pati en codi",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "segon-cicle",
      "cicleLabel": "Segon cicle",
      "tematica": "art",
      "tematicaLabel": "Música i expressió",
      "materia": "artistica",
      "materiaLabel": "Música i Tecnologia",
      "sessions": "5 sessions",
      "repte": "Com podem convertir una idea rítmica en instruccions que altres persones i la micro:bit puguen interpretar?"
    },
    {
      "id": "situacio-sa-mb-targetes-paraules",
      "slug": "mb-targetes-paraules",
      "url": "situacio/mb-targetes-paraules/index.html",
      "titol": "Paraules en targetes digitals",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "llengua",
      "tematicaLabel": "Vocabulari i representació",
      "materia": "llengua",
      "materiaLabel": "Llengües, Art i Tecnologia",
      "sessions": "5 sessions",
      "repte": "Com podem dissenyar una targeta digital que ajude a recordar vocabulari amb icones, seqüències i temps d’espera?"
    },
    {
      "id": "situacio-sa-mb-tecnologia-benestar",
      "slug": "mb-tecnologia-benestar",
      "url": "situacio/mb-tecnologia-benestar/index.html",
      "titol": "Tecnologia per al benestar quotidià",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle i ESO",
      "tematica": "ciutadania",
      "tematicaLabel": "Disseny responsable i benestar",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Ciències i Ciutadania",
      "sessions": "5 sessions",
      "repte": "Com podem dissenyar una ajuda tecnològica senzilla que facilite una rutina de benestar sense vigilar ni diagnosticar ningú?"
    },
    {
      "id": "situacio-sa-mb-xifres-que-viatgen",
      "slug": "mb-xifres-que-viatgen",
      "url": "situacio/mb-xifres-que-viatgen/index.html",
      "titol": "Xifres que viatgen",
      "robot": "microbit",
      "robotLabel": "micro:bit",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "historia",
      "tematicaLabel": "Missatges i patrimoni",
      "materia": "tecnologia",
      "materiaLabel": "Història, Matemàtiques i Programació",
      "sessions": "4 sessions",
      "repte": "Com podem codificar i descodificar un missatge amb un algorisme, i quins límits té el xifrat de Cèsar?"
    },
    {
      "id": "situacio-sa-mercat-tangible",
      "slug": "mercat-tangible",
      "url": "situacio/mercat-tangible/index.html",
      "titol": "Ruta Saludable pel Mercat del Barri",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "cicle": "primer-cicle",
      "cicleLabel": "Primer cicle",
      "tematica": "salut",
      "tematicaLabel": "Salut, hàbits i benestar",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques",
      "sessions": "4 sessions",
      "repte": "Com podem planificar la compra de fruites i verdures de temporada al mercat gastant el pressupost just i fent el camí més curt?"
    },
    {
      "id": "situacio-sa-residus-lego",
      "slug": "residus-lego",
      "url": "situacio/residus-lego/index.html",
      "titol": "Eco-Planta de Reciclatge Intel·ligent",
      "robot": "spike",
      "robotLabel": "Spike",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Medi ambient i sostenibilitat",
      "materia": "medi",
      "materiaLabel": "Coneixement del Medi / Ciències",
      "sessions": "5 sessions",
      "repte": "Com podem automatitzar la separació d'envasos, vidre i paper al menjador de l'escola per augmentar el percentatge de reciclatge?"
    },
    {
      "id": "situacio-sa-sp-ajudant-receptes",
      "slug": "sp-ajudant-receptes",
      "url": "situacio/sp-ajudant-receptes/index.html",
      "titol": "Un ajudant de receptes en maqueta",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "salut",
      "tematicaLabel": "Alimentació i vida quotidiana",
      "materia": "medi",
      "materiaLabel": "Coneixement del Medi, Matemàtiques i Tecnologia",
      "sessions": "5 sessions",
      "repte": "Com podem prototipar un ajudant mecànic per a una tasca de cuina i fer que siga fàcil i segur d’utilitzar?"
    },
    {
      "id": "situacio-sa-sp-benvinguda",
      "slug": "sp-benvinguda",
      "url": "situacio/sp-benvinguda/index.html",
      "titol": "Una benvinguda amb moviment",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "societat",
      "tematicaLabel": "Acollida i convivència",
      "materia": "llengua",
      "materiaLabel": "Llengua, Art i Tecnologia",
      "sessions": "5 sessions",
      "repte": "Com podem dissenyar una màquina amb SPIKE Prime que reba les persones amb un moviment amable i fàcil d’entendre?"
    },
    {
      "id": "situacio-sa-sp-biblioteca-circulant",
      "slug": "sp-biblioteca-circulant",
      "url": "situacio/sp-biblioteca-circulant/index.html",
      "titol": "El centre logístic de la biblioteca",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "societat",
      "tematicaLabel": "Biblioteca i comunitat",
      "materia": "matematiques",
      "materiaLabel": "Matemàtiques, Tecnologia i Ciutadania Digital",
      "sessions": "7 sessions",
      "repte": "Com podem preparar, traçar, protegir i verificar un paquet de llibres en una maqueta sense exposar dades personals?"
    },
    {
      "id": "situacio-sa-sp-caminada-impossible",
      "slug": "sp-caminada-impossible",
      "url": "situacio/sp-caminada-impossible/index.html",
      "titol": "La desfilada de les caminades impossibles",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "art",
      "tematicaLabel": "Moviment i disseny",
      "materia": "medi",
      "materiaLabel": "Física, Matemàtiques i Tecnologia",
      "sessions": "5 sessions",
      "repte": "Com podem fer avançar un model LEGO SPIKE Prime sense rodes i quins canvis de les potes n’alteren el moviment?"
    },
    {
      "id": "situacio-sa-sp-dades-pati",
      "slug": "sp-dades-pati",
      "url": "situacio/sp-dades-pati/index.html",
      "titol": "El pati: dades, ritme i decisions",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Pati, clima i cura de l’hort",
      "materia": "medi",
      "materiaLabel": "Ciències, Matemàtiques, Música i Tecnologia",
      "sessions": "10–12 sessions",
      "repte": "Com podem dissenyar programes amb variables i dades per a un festival escolar, comprovant la fiabilitat de cada decisió?"
    },
    {
      "id": "situacio-sa-sp-debug-rutes",
      "slug": "sp-debug-rutes",
      "url": "situacio/sp-debug-rutes/index.html",
      "titol": "Depurar per arribar-hi",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle i ESO",
      "tematica": "depuracio",
      "tematicaLabel": "Depuració i mobilitat",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Pensament Computacional",
      "sessions": "6 lliçons · 7–10 sessions",
      "repte": "Com distingim un error de muntatge d’un error de programa i com demostrem que una ruta autònoma funciona de manera fiable?"
    },
    {
      "id": "situacio-sa-sp-disseny-iteratiu",
      "slug": "sp-disseny-iteratiu",
      "url": "situacio/sp-disseny-iteratiu/index.html",
      "titol": "Dissenyar, provar i compartir",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle i ESO",
      "tematica": "disseny",
      "tematicaLabel": "Disseny iteratiu i comunicació",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Llengües i Emprenedoria",
      "sessions": "6 lliçons · 7–9 sessions",
      "repte": "Com transformem una idea útil en un prototip provat i en una explicació que ajude altres persones a valorar-la?"
    },
    {
      "id": "situacio-sa-sp-eines-missio-eva",
      "slug": "sp-eines-missio-eva",
      "url": "situacio/sp-eines-missio-eva/index.html",
      "titol": "Eines per a una missió de servei espacial",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "espai",
      "tematicaLabel": "Exploració i enginyeria espacial",
      "materia": "medi",
      "materiaLabel": "Ciències, Tecnologia i Disseny",
      "sessions": "5 sessions",
      "repte": "Com podem dissenyar una eina que ajude una persona amb guants a moure peces o guiar un cable en una reparació simulada?"
    },
    {
      "id": "situacio-sa-sp-fonaments-fisics",
      "slug": "sp-fonaments-fisics",
      "url": "situacio/sp-fonaments-fisics/index.html",
      "titol": "Robots que ens ajuden",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle i ESO",
      "tematica": "robotica",
      "tematicaLabel": "Computació física i professions",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Ciències i Orientació",
      "sessions": "6 lliçons · 6–8 sessions",
      "repte": "Què fa que una màquina siga un robot i com podem combinar maquinari, programa i treball en equip per resoldre una necessitat real?"
    },
    {
      "id": "situacio-sa-sp-museu-accessible",
      "slug": "sp-museu-accessible",
      "url": "situacio/sp-museu-accessible/index.html",
      "titol": "Laboratori de solucions accessibles",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "societat",
      "tematicaLabel": "Disseny per a la comunitat",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Disseny i Matemàtiques",
      "sessions": "8–10 sessions",
      "repte": "Com podem identificar una necessitat, prototipar alternatives i millorar una solució accessible amb proves justes?"
    },
    {
      "id": "situacio-sa-sp-prime-combinat",
      "slug": "sp-prime-combinat",
      "url": "situacio/sp-prime-combinat/index.html",
      "titol": "Casa eficient i collita delicada",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Energia i agricultura de proximitat",
      "materia": "medi",
      "materiaLabel": "Ciències, Tecnologia i Matemàtiques",
      "sessions": "7–8 sessions",
      "repte": "Com podem automatitzar una acció quotidiana de menor impacte i dissenyar una eina que manege el fruit amb suavitat?"
    },
    {
      "id": "situacio-sa-sp-rampa-dades",
      "slug": "sp-rampa-dades",
      "url": "situacio/sp-rampa-dades/index.html",
      "titol": "Energia en una pista de proves",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Moviment i energia",
      "materia": "medi",
      "materiaLabel": "Ciències, Matemàtiques i Tecnologia",
      "sessions": "6 sessions",
      "repte": "Què podem inferir sobre energia i moviment amb un vehicle de maqueta, i com descrivim l’error de les nostres mesures?"
    },
    {
      "id": "situacio-sa-sp-reg-hort",
      "slug": "sp-reg-hort",
      "url": "situacio/sp-reg-hort/index.html",
      "titol": "Un indicador de reg per a l’hort escolar",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Agricultura i dades meteorològiques",
      "materia": "medi",
      "materiaLabel": "Ciències, Matemàtiques i Tecnologia",
      "sessions": "3 sessions de 45–60 min",
      "repte": "Com podem transformar la previsió de pluja d’una setmana en un indicador calibrat i útil per a prendre una decisió sobre una maqueta d’hort?"
    },
    {
      "id": "situacio-sa-sp-reptes-cooperatius",
      "slug": "sp-reptes-cooperatius",
      "url": "situacio/sp-reptes-cooperatius/index.html",
      "titol": "Reptes cooperatius de taller",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "societat",
      "tematicaLabel": "Cooperació i creativitat",
      "materia": "tecnologia",
      "materiaLabel": "Tecnologia, Matemàtiques i Llengua",
      "sessions": "5 sessions",
      "repte": "Com podem generar idees, explicar per a què serveixen i convertir-les en un repte mecànic cooperatiu?"
    },
    {
      "id": "situacio-sa-sp-titelles-moviment",
      "slug": "sp-titelles-moviment",
      "url": "situacio/sp-titelles-moviment/index.html",
      "titol": "Titelles mecàniques de l’Albufera",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "art",
      "tematicaLabel": "Relat, natura i expressió",
      "materia": "artistica",
      "materiaLabel": "Educació Artística, Llengua i Tecnologia",
      "sessions": "5 sessions",
      "repte": "Com podem transformar el gir d’un motor en el moviment expressiu d’una titella que conta una història local?"
    },
    {
      "id": "situacio-sa-sp-vent-model",
      "slug": "sp-vent-model",
      "url": "situacio/sp-vent-model/index.html",
      "titol": "Un indicador per a llegir dades de vent",
      "robot": "spike",
      "robotLabel": "SPIKE Prime",
      "cicle": "tercer-cicle",
      "cicleLabel": "Tercer cicle",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Meteorologia i dades",
      "materia": "medi",
      "materiaLabel": "Ciències, Matemàtiques i Tecnologia",
      "sessions": "3 sessions de 45–60 min",
      "repte": "Com podem convertir la velocitat prevista del vent en una representació calibrada, comparable i comprensible?"
    },
    {
      "id": "situacio-sa-tale-bot-biblioteca-barri",
      "slug": "tale-bot-biblioteca-barri",
      "url": "situacio/tale-bot-biblioteca-barri/index.html",
      "titol": "Una ruta de contes per la biblioteca",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil (4-5 anys)",
      "tematica": "societat",
      "tematicaLabel": "Convivència i ciutadania",
      "materia": "llengua",
      "materiaLabel": "Llengua i Literatura",
      "sessions": "3 sessions",
      "repte": "Quina ruta pot seguir el robot per visitar tres espais de lectura, i com podem inventar una història diferent en cada parada?"
    },
    {
      "id": "situacio-sa-tale-bot-cami-llavors",
      "slug": "tale-bot-cami-llavors",
      "url": "situacio/tale-bot-cami-llavors/index.html",
      "titol": "El camí de les llavors",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil (4-5 anys)",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Medi ambient i sostenibilitat",
      "materia": "medi",
      "materiaLabel": "Descoberta de l’entorn",
      "sessions": "3 sessions",
      "repte": "Com podem fer arribar les llavors als bancals del jardí i explicar què necessita cada planta per créixer?"
    },
    {
      "id": "situacio-sa-tale-bot-dibuix-pati",
      "slug": "tale-bot-dibuix-pati",
      "url": "situacio/tale-bot-dibuix-pati/index.html",
      "titol": "Dibuixem un pati que convida a jugar",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil (4-5 anys)",
      "tematica": "ciutat",
      "tematicaLabel": "Ciutat intel·ligent i accessibilitat",
      "materia": "artistica",
      "materiaLabel": "Educació Artística",
      "sessions": "3 sessions",
      "repte": "Quines formes i espais podem representar perquè el plànol del pati siga fàcil d’entendre i permeta més d’una manera de jugar?"
    },
    {
      "id": "situacio-sa-tale-bot-mapa-sonor",
      "slug": "tale-bot-mapa-sonor",
      "url": "situacio/tale-bot-mapa-sonor/index.html",
      "titol": "El mapa sonor del barri",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil (4-5 anys)",
      "tematica": "societat",
      "tematicaLabel": "Convivència i ciutadania",
      "materia": "llengua",
      "materiaLabel": "Llengua i Literatura",
      "sessions": "3 sessions",
      "repte": "Com podem representar sons i veus d’un barri imaginari sense confondre el mapa amb una gravació real del nostre entorn?"
    },
    {
      "id": "situacio-sa-tb-carrers-amables",
      "slug": "tb-carrers-amables",
      "url": "situacio/tb-carrers-amables/index.html",
      "titol": "Un barri que es mou amb cura",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot Pro",
      "cicle": "segon-cicle-infantil",
      "cicleLabel": "Educació Infantil i primer cicle",
      "tematica": "societat",
      "tematicaLabel": "Mobilitat i convivència",
      "materia": "medi",
      "materiaLabel": "Medi, Matemàtiques i Pensament Computacional",
      "sessions": "4 sessions",
      "repte": "Com podem traçar un recorregut pel barri que siga fàcil de seguir, segur i còmode per a diferents persones?"
    },
    {
      "id": "situacio-sa-tb-escola-descobertes",
      "slug": "tb-escola-descobertes",
      "url": "situacio/tb-escola-descobertes/index.html",
      "titol": "La fira de descobertes de l'escola",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "cicle": "segon-cicle-infantil",
      "cicleLabel": "Infantil i primer cicle",
      "tematica": "comunitat",
      "tematicaLabel": "Escola i barri",
      "materia": "medi",
      "materiaLabel": "Coneixement del Medi, Matemàtiques, Llenguatge i Educació Artística",
      "sessions": "7 sessions",
      "repte": "Com podem preparar una fira on cada ruta del robot convide a observar, comptar, conversar i crear?"
    },
    {
      "id": "situacio-sa-tb-explora-el-barri",
      "slug": "tb-explora-el-barri",
      "url": "situacio/tb-explora-el-barri/index.html",
      "titol": "Explorem el barri amb Tale-Bot",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "cicle": "segon-cicle-infantil",
      "cicleLabel": "Infantil i primer cicle",
      "tematica": "entorn",
      "tematicaLabel": "Exploració de l’entorn",
      "materia": "pensament-computacional",
      "materiaLabel": "Ciències, Matemàtiques, Llenguatge i Art",
      "sessions": "15 activitats",
      "repte": "Com podem utilitzar una ruta programada per a observar, ordenar i contar històries sobre el nostre entorn?"
    },
    {
      "id": "situacio-sa-tb-missions-comunitat",
      "slug": "tb-missions-comunitat",
      "url": "situacio/tb-missions-comunitat/index.html",
      "titol": "Missions de comunitat amb Tale-Bot",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "cicle": "segon-cicle-infantil",
      "cicleLabel": "Infantil i primer cicle",
      "tematica": "entorn",
      "tematicaLabel": "Relats i serveis comunitaris",
      "materia": "pensament-computacional",
      "materiaLabel": "Llenguatge, Medi Social i Pensament Computacional",
      "sessions": "10 activitats",
      "repte": "Com organitzem un recorregut que visite diversos llocs i conte una història que el grup puga canviar?"
    },
    {
      "id": "situacio-sa-tb-ordres-en-accio",
      "slug": "tb-ordres-en-accio",
      "url": "situacio/tb-ordres-en-accio/index.html",
      "titol": "Ordres en acció amb Tale-Bot",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "cicle": "segon-cicle-infantil",
      "cicleLabel": "Infantil i primer cicle",
      "tematica": "programacio",
      "tematicaLabel": "Seqüències i instruccions",
      "materia": "pensament-computacional",
      "materiaLabel": "Pensament computacional, Llenguatge i Matemàtiques",
      "sessions": "10 activitats breus",
      "repte": "Com podem donar instruccions clares perquè Tale-Bot arribe, salude, dance i complete una missió?"
    },
    {
      "id": "situacio-sa-tb-patrons-en-ruta",
      "slug": "tb-patrons-en-ruta",
      "url": "situacio/tb-patrons-en-ruta/index.html",
      "titol": "Patrons en ruta amb Tale-Bot",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "cicle": "segon-cicle-infantil",
      "cicleLabel": "Infantil i primer cicle",
      "tematica": "programacio",
      "tematicaLabel": "Patrons i repetició",
      "materia": "pensament-computacional",
      "materiaLabel": "Matemàtiques, Música i Pensament Computacional",
      "sessions": "7 reptes",
      "repte": "Quina part d’una ruta es repeteix i com podem expressar-la amb menys ordres sense perdre precisió?"
    },
    {
      "id": "situacio-sa-tb-rastre-corral",
      "slug": "tb-rastre-corral",
      "url": "situacio/tb-rastre-corral/index.html",
      "titol": "El rastre del corral",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot Pro",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "entorn",
      "tematicaLabel": "Animals i entorn",
      "materia": "pensament-computacional",
      "materiaLabel": "Descoberta de l’entorn i Pensament Computacional",
      "sessions": "3 sessions",
      "repte": "Com podem preparar un mapa amb files, columnes i una orientació inicial perquè Tale-Bot trobe cinc animals amb ordres cap avant que puguem comptar i comprovar?"
    },
    {
      "id": "situacio-sa-tren-transport",
      "slug": "tren-transport",
      "url": "situacio/tren-transport/index.html",
      "titol": "La Línia Verda del Tren Sostenible",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "cicle": "infantil",
      "cicleLabel": "Educació Infantil",
      "tematica": "sostenibilitat",
      "tematicaLabel": "Medi ambient i sostenibilitat",
      "materia": "medi",
      "materiaLabel": "Coneixement del Medi / Ciències",
      "sessions": "3 sessions",
      "repte": "Com transportem les mercaderies del camp a la ciutat escollint recorreguts i senyals que facin el viatge segur i fàcil de seguir?"
    }
  ],
  "tutorials": [
    {
      "id": "tutorial-ce-bifurcacions",
      "slug": "ce-bifurcacions",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "url": "tutorial/ce-bifurcacions/index.html",
      "titol": "Canvis d'agulla i bifurcacions en Y",
      "dificultat": "Intermedi",
      "durada": "45 min",
      "descripcio": "Utilitzar peces de canvi de via per crear rutes alternatives i prendre decisions de transport segons el destí."
    },
    {
      "id": "tutorial-ce-bucles",
      "slug": "ce-bucles",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "url": "tutorial/ce-bucles/index.html",
      "titol": "El bucle ferroviari: repetir un recorregut",
      "dificultat": "Iniciació",
      "durada": "40 min",
      "descripcio": "Explorar la repetició amb una via tancada, fer prediccions i comparar el bucle físic amb una seqüència d’accions."
    },
    {
      "id": "tutorial-ce-motors-sensors",
      "slug": "ce-motors-sensors",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "url": "tutorial/ce-motors-sensors/index.html",
      "titol": "Motors i sensors: Els maons d'acció de colors",
      "dificultat": "Iniciació",
      "durada": "45 min",
      "descripcio": "Descobrir la relació causa-efecte col·locant els 5 maons de colors a les vies per activar sensors, sons i canvis de marxa."
    },
    {
      "id": "tutorial-ce-primeres-passes",
      "slug": "ce-primeres-passes",
      "robot": "coding-express",
      "robotLabel": "Coding Express",
      "url": "tutorial/ce-primeres-passes/index.html",
      "titol": "Primeres passes: El circuit bàsic i el motor Push & Go",
      "dificultat": "Iniciació",
      "durada": "30 min",
      "descripcio": "Com encendre la locomotora, comprendre la mecànica 'empeny per arrencar i atura amb la mà' i muntar el primer circuit tancat de vies."
    },
    {
      "id": "tutorial-cr-motors-sensors",
      "slug": "cr-motors-sensors",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "url": "tutorial/cr-motors-sensors/index.html",
      "titol": "Motors i sensors: Esquivador d'obstacles amb infrarojos",
      "dificultat": "Intermedi",
      "durada": "45 min",
      "descripcio": "Utilitzar les erugues de Rocky i el sensor frontal per aturar-se o girar abans de xocar contra una paret."
    },
    {
      "id": "tutorial-cr-primeres-passes",
      "slug": "cr-primeres-passes",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "url": "tutorial/cr-primeres-passes/index.html",
      "titol": "Primeres passes: Connexió a mBlock 5 i cares a la matriu LED",
      "dificultat": "Iniciació",
      "durada": "35 min",
      "descripcio": "Connectar Codey al software de l'ordinador o tauleta i programar animacions facials i missatges lliscants."
    },
    {
      "id": "tutorial-cr-veu-ia",
      "slug": "cr-veu-ia",
      "robot": "codey-rocky",
      "robotLabel": "Codey Rocky",
      "url": "tutorial/cr-veu-ia/index.html",
      "titol": "Reconeixement de veu i Intel·ligència Artificial",
      "dificultat": "Avançat",
      "durada": "50 min",
      "descripcio": "Utilitzar l'extensió de Serveis Cognitius per controlar el moviment del robot mitjançant ordres de veu en català."
    },
    {
      "id": "tutorial-cs-bucles",
      "slug": "cs-bucles",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "url": "tutorial/cs-bucles/index.html",
      "titol": "Bucles de repetició i estructures de control",
      "dificultat": "Intermedi",
      "durada": "45 min",
      "descripcio": "Empaquetar conjunts d'instruccions dins de blocs de bucle per crear figures regulars i camins repetitius."
    },
    {
      "id": "tutorial-cs-motors-sensors",
      "slug": "cs-motors-sensors",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "url": "tutorial/cs-motors-sensors/index.html",
      "titol": "Motors i paràmetres numèrics",
      "dificultat": "Intermedi",
      "durada": "40 min",
      "descripcio": "Optimitzar el codi combinant les fitxes direccionals amb blocs de números (1, 2, 3, 4, 5) per estalviar espai al tauler."
    },
    {
      "id": "tutorial-cs-primeres-passes",
      "slug": "cs-primeres-passes",
      "robot": "coding-set",
      "robotLabel": "Coding Set",
      "url": "tutorial/cs-primeres-passes/index.html",
      "titol": "Primeres passes: La torre de lectura i el tauler físic",
      "dificultat": "Iniciació",
      "durada": "30 min",
      "descripcio": "Descobrir la connexió entre la torre d'escaneig i el MatataBot, i l'ordre seqüencial d'esquerra a dreta."
    },
    {
      "id": "tutorial-mb-fanalet-llum",
      "slug": "mb-fanalet-llum",
      "robot": "microbit",
      "robotLabel": "Micro:bit",
      "url": "tutorial/mb-fanalet-llum/index.html",
      "titol": "micro:bit: un fanalet que respon a la llum",
      "dificultat": "Iniciació",
      "durada": "35 min",
      "descripcio": "Llegir la llum ambiental amb la matriu LED i encendre una icona quan l’entorn s’enfosqueix."
    },
    {
      "id": "tutorial-mb-motors-sensors",
      "slug": "mb-motors-sensors",
      "robot": "microbit",
      "robotLabel": "Micro:bit",
      "url": "tutorial/mb-motors-sensors/index.html",
      "titol": "Motors i sensors: Sensor d'humitat i servomotors",
      "dificultat": "Intermedi",
      "durada": "50 min",
      "descripcio": "Connectar sensors externs als pins de la vora (P0, P1, P2) amb pinces de cocodril per automatitzar una alarma de reg."
    },
    {
      "id": "tutorial-mb-primeres-passes",
      "slug": "mb-primeres-passes",
      "robot": "microbit",
      "robotLabel": "Micro:bit",
      "url": "tutorial/mb-primeres-passes/index.html",
      "titol": "Primeres passes: MakeCode, matriu de 25 LEDs i polsadors",
      "dificultat": "Iniciació",
      "durada": "30 min",
      "descripcio": "Com programar la placa des del navegador web MakeCode sense instal·lar cap programa i descarregar l'arxiu .hex."
    },
    {
      "id": "tutorial-mb-radio-mesh",
      "slug": "mb-radio-mesh",
      "robot": "microbit",
      "robotLabel": "Micro:bit",
      "url": "tutorial/mb-radio-mesh/index.html",
      "titol": "Xarxa de ràdio sense fils: Walkie-talkie i sensors remots",
      "dificultat": "Intermedi",
      "durada": "45 min",
      "descripcio": "Connectar diverses micro:bits de l'aula entre si utilitzant l'antena de ràdio integrada sense necessitat de Wi-Fi."
    },
    {
      "id": "tutorial-mb-so-microfon",
      "slug": "mb-so-microfon",
      "robot": "microbit",
      "robotLabel": "Micro:bit",
      "url": "tutorial/mb-so-microfon/index.html",
      "titol": "Micròfon i so: Detector de soroll i aplaudiments (V2)",
      "dificultat": "Iniciació",
      "durada": "35 min",
      "descripcio": "Utilitzar el micròfon MEMS de la versió 2 per controlar el nivell de decibels de l'aula o encendre un llum en picar de mans."
    },
    {
      "id": "tutorial-sp-brac-sensor-forca",
      "slug": "sp-brac-sensor-forca",
      "robot": "spike",
      "robotLabel": "Spike",
      "url": "tutorial/sp-brac-sensor-forca/index.html",
      "titol": "Braç robòtic i sensor de força",
      "dificultat": "Avançat",
      "durada": "55 min",
      "descripcio": "Construir una pinça que detecti el contacte i utilitzar les lectures del sensor de força per provar un límit programat."
    },
    {
      "id": "tutorial-sp-distancia",
      "slug": "sp-distancia",
      "robot": "spike",
      "robotLabel": "Spike",
      "url": "tutorial/sp-distancia/index.html",
      "titol": "SPIKE Prime: calcular una parada sense tocar l’obstacle",
      "dificultat": "Intermedi",
      "durada": "45 min",
      "descripcio": "Ajustar el recorregut d’una base motriu amb girs de roda i comparar el càlcul amb una parada per contacte."
    },
    {
      "id": "tutorial-sp-motors-sensors",
      "slug": "sp-motors-sensors",
      "robot": "spike",
      "robotLabel": "Spike",
      "url": "tutorial/sp-motors-sensors/index.html",
      "titol": "Motors i sensors: Tren d'engranatges i sensor de color",
      "dificultat": "Intermedi",
      "durada": "50 min",
      "descripcio": "Muntar un vehicle amb reductora d'engranatges per guanyar força i aturar-lo exactament davant d'una línia vermella."
    },
    {
      "id": "tutorial-sp-primeres-passes",
      "slug": "sp-primeres-passes",
      "robot": "spike",
      "robotLabel": "Spike",
      "url": "tutorial/sp-primeres-passes/index.html",
      "titol": "Primeres passes: El Hub intel·ligent i el primer programa",
      "dificultat": "Iniciació",
      "durada": "35 min",
      "descripcio": "Connexió del Hub per Bluetooth a l'App SPIKE, gestió de la matriu 5x5 de LEDs i bateria recarregable."
    },
    {
      "id": "tutorial-tb-motors-sensors",
      "slug": "tb-motors-sensors",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "url": "tutorial/tb-motors-sensors/index.html",
      "titol": "Motors i sensors: Dibuix geomètric amb retoladors",
      "dificultat": "Intermedi",
      "durada": "45 min",
      "descripcio": "Inserir dos retoladors a les ales de TaleBot per traçar formes geomètriques de colors exactes sobre paper continu."
    },
    {
      "id": "tutorial-tb-primeres-passes",
      "slug": "tb-primeres-passes",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot Pro",
      "url": "tutorial/tb-primeres-passes/index.html",
      "titol": "Primeres passes: comandaments i distància",
      "dificultat": "Iniciació",
      "durada": "30 min",
      "descripcio": "Prepara Tale-Bot Pro, tria la longitud de pas i programa una seqüència curta amb les tecles direccionals."
    },
    {
      "id": "tutorial-tb-reconeixement-veu",
      "slug": "tb-reconeixement-veu",
      "robot": "tale-bot",
      "robotLabel": "Tale-Bot",
      "url": "tutorial/tb-reconeixement-veu/index.html",
      "titol": "Reconeixement i enregistrament de veu",
      "dificultat": "Iniciació",
      "durada": "40 min",
      "descripcio": "Gravar pistes d'àudio i diàlegs personalitzats amb la veu de l'alumnat a cada etapa del recorregut."
    }
  ],
  "robots": [
    {
      "id": "robot-coding-express",
      "slug": "coding-express",
      "prefix": "ce",
      "nom": "Coding Express",
      "edat": "2-5 anys",
      "descripcio": "El tren interactiu dels colors i el pensament computacional primerenc.",
      "colors": [
        "#e4242b",
        "#fec002"
      ],
      "order": 1,
      "url": "robot/coding-express/index.html",
      "tutorials": 4
    },
    {
      "id": "robot-tale-bot",
      "slug": "tale-bot",
      "prefix": "tb",
      "nom": "Tale-Bot",
      "edat": "3-7 anys",
      "descripcio": "El robot narrador que parla, llegeix mapes interactius i dibuixa.",
      "colors": [
        "#fc8439",
        "#804cbd"
      ],
      "order": 2,
      "url": "robot/tale-bot/index.html",
      "tutorials": 3
    },
    {
      "id": "robot-coding-set",
      "slug": "coding-set",
      "prefix": "cs",
      "nom": "Coding Set",
      "edat": "4-9 anys",
      "descripcio": "Programació tangible sense pantalles amb Matatalab.",
      "colors": [
        "#fc7813",
        "#60a62d"
      ],
      "order": 3,
      "url": "robot/coding-set/index.html",
      "tutorials": 3
    },
    {
      "id": "robot-codey-rocky",
      "slug": "codey-rocky",
      "prefix": "cr",
      "nom": "Codey Rocky",
      "edat": "6-12 anys",
      "descripcio": "El robot amb pantalla LED 16 × 8, sensors i moviment amb orugues.",
      "colors": [
        "#0079dc",
        "#fdc80a"
      ],
      "order": 4,
      "url": "robot/codey-rocky/index.html",
      "tutorials": 3
    },
    {
      "id": "robot-spike",
      "slug": "spike",
      "prefix": "sp",
      "nom": "Spike",
      "edat": "10-16 anys",
      "descripcio": "Mecatrònica, engranatges i sensors d'alta precisió de LEGO Education.",
      "colors": [
        "#d82098",
        "#fddc3e"
      ],
      "order": 5,
      "url": "robot/spike/index.html",
      "tutorials": 4
    },
    {
      "id": "robot-microbit",
      "slug": "microbit",
      "prefix": "mb",
      "nom": "Micro:bit",
      "edat": "9-18 anys",
      "descripcio": "La placa microcontroladora per a projectes oberts i ciutadans.",
      "colors": [
        "#047fdf",
        "#4a515d"
      ],
      "order": 6,
      "url": "robot/microbit/index.html",
      "tutorials": 5
    }
  ]
};
